ApollosProject/apollos-apps

.github/ISSUE_TEMPLATE.md

In an effort to be more product and user minded this updates the issue template to use a user story to reflect the desires of the issue from the context of the user.

User focused issue template

---

.travis.yml
api/.eslintignore
mobile/.eslintignore
mobile/package.json

Fixes #4 
This PR implements CI with our Jest Unit tests.

testing and travis integrations

---

mobile/android/gradle/wrapper/gradle-wrapper.properties
mobile/ios/apolloschurchapp.xcodeproj/project.pbxproj
mobile/ios/apolloschurchapp/Info.plist

Updates the bundle id so that we can connect the app to the itunesconnect store.

updated the bundle id for ios

---

.travis.yml
api/package.json
mobile/package.json
scripts/global-npm-script.sh
scripts/test-script.sh

This is a fix to our long tests timing out in Travis. I want to look into a way in which we don't have to use Travis_wait to solve this issue. https://randyzwitch.com/travisci-10minute-timeout-build-error/ has interesting solutions that I will look into later.

Travis wait

---

.travis.yml
api/package.json

Added env variables and improved travis script for NOW

Fixes now ci

---

api/__mocks__/isomorphic-fetch.js
api/__mocks__/rock-api-mocks/index.js
api/__mocks__/rock-api-mocks/people.js
api/src/connectors/rock/Model.js
api/src/connectors/rock/__tests__/Model.tests.js
api/src/data/content-channels/index.js
api/src/data/content-items/index.js
api/src/data/index.js
api/src/data/node/resolver.js
api/src/data/people/__tests__/__snapshots__/model.tests.js.snap
api/src/data/people/__tests__/__snapshots__/resolvers.test.js.snap
api/src/data/people/__tests__/model.tests.js
api/src/data/people/__tests__/resolvers.test.js
api/src/data/people/index.js
api/src/data/people/model.js
api/src/data/people/resolver.js
api/src/data/people/schema.js

Fixes #7.
This is just the initial setup for the people schema.

7 people schema

---

mobile/src/ui/TableView/Cell.js
mobile/src/ui/TableView/CellIcon.js
mobile/src/ui/TableView/CellText.js
mobile/src/ui/TableView/Divider.js
mobile/src/ui/TableView/FormFields.js
mobile/src/ui/TableView/TableView.stories.js
mobile/src/ui/TableView/TableView.tests.js
mobile/src/ui/TableView/__snapshots__/TableView.tests.js.snap
mobile/src/ui/TableView/index.js

Copied over NewSpring TableView

---

CHANGELOG.md
mobile/android/app/build.gradle
mobile/ios/apolloschurchapp-tvOS/Info.plist
mobile/ios/apolloschurchapp-tvOSTests/Info.plist
mobile/ios/apolloschurchapp/Info.plist
mobile/ios/apolloschurchappTests/Info.plist
mobile/package.json
mobile/yarn.lock

This gives us the ability to update the project files for android and ios by the `package.json` file.

Update versioning for iOS and Android binary

---

CHANGELOG.md
mobile/package-lock.json
mobile/src/tabs/connect/index.js
mobile/src/ui/TableView/index.js

Added TableView connect menu to connect tab 

---

mobile/android/app/build.gradle

Updates android id to fix issue with android signing. (Created a new app)

updated android id

---

api/__mocks__/isomorphic-fetch.js
api/package.json
api/src/connectors/__tests__/__snapshots__/rest.js.snap
api/src/connectors/__tests__/rest.js
api/src/connectors/rest.js
api/src/connectors/rock/Model.js
api/src/connectors/rock/RequestBuilder.js
api/src/data/auth/__tests__/__snapshots__/index.tests.js.snap
api/src/data/auth/__tests__/index.tests.js
api/src/data/auth/index.js
api/src/data/auth/model.js
api/src/data/content-channels/__tests__/__snapshots__/model.tests.js.snap
api/src/data/content-items/__tests__/__snapshots__/model.tests.js.snap
api/src/data/index.js
api/src/data/people/__tests__/__snapshots__/model.tests.js.snap
api/src/data/people/__tests__/resolvers.test.js
api/src/index.js
api/yarn.lock

Implementation of an `authenticate` mutation that authenticates a user with Rock. Example mutation:
Example:
```gql
mutation {
authenticate(identity: "myuser", password: "mypassword") {
token
user {
id
}
}
}
```
The token it returns is a JWT token with an expiration date of 60days. On Heighliner we explicitly used `email` in the login mutation. I've simplified the process to take any identity that rock recognizes. Which removes some special-case handling.
I'm also opting to use Rock's cookie-based authentication flow, even on the server. It appears to be the best way to do user-auth with the Rock api. So the token that we get back from this authenticate mutation actually has Rock's cookie encoded in it.
To authenticate against the API in future requests, use the `token` provided in a …

User Authentication

---

.travis.yml

Fixes scaling issues for now deployment.

fix now deployment scaling

---

.travis.yml

Set Team Scope for Now Deployments

---

.travis.yml

Set Now Team scope

---

mobile/android/app/build.gradle
mobile/ios/apolloschurchapp.xcodeproj/project.pbxproj
mobile/ios/apolloschurchapp.xcodeproj/xcshareddata/xcschemes/apolloschurchapp-dev.xcscheme
mobile/ios/apolloschurchapp.xcodeproj/xcshareddata/xcschemes/apolloschurchapp.xcscheme

Fix Android Studio and Xcode build errors

---

README.md
mobile/android/app/build.gradle
mobile/android/build.gradle
mobile/android/gradle.properties
mobile/android/gradle/wrapper/gradle-wrapper.properties
mobile/ios/apolloschurchapp/Info.plist
mobile/package.json

Fixes capability issues with android builds and updates version number.

---

CHANGELOG.md
api/package.json
mobile/android/app/build.gradle
mobile/ios/apolloschurchapp/Info.plist
mobile/package.json

Updates version number to v0.3.0 

---

mobile/ios/apolloschurchapp/Info.plist

add export compliance to xcode

---

api/package.json

8.11.3 update

---

mobile/package.json

added node engine to package.json

---

mobile/appcenter-post-clone.sh

Created post clone script for building app-center

---

mobile/android/app/release/output.json
mobile/android/gradle.properties
mobile/android/gradle.properties.appcenter
mobile/appcenter-pre-build.sh

add enableAapt2 to gradle.props

---

mobile/App.js
mobile/src/client/index.js
mobile/storybook/storybook.js

Fixes infinite splashscreen in storybook 😇😬

Fix infinite splashscreen in storybook

---

api/__mocks__/apollo-datasource-mocks/index.js
api/__mocks__/apollo-datasource-mocks/live-stream.js
api/__mocks__/apollo-server-env.js
api/src/data/live/__tests__/__snapshots__/resolver.tests.js.snap
api/src/data/live/__tests__/resolver.tests.js
api/src/getDataSources.js
api/src/index.js
api/src/utils/testUtils.js

Testing support for Apollo Datasources

---

README.md
scripts/change-log/generate-git-log.sh

Created documentation for creating a release within the Apollos Church App

---

mobile/src/client/authLink.js
mobile/src/content-feed/index.js
mobile/src/content-single/index.js
mobile/src/live/LiveButton.js
mobile/src/tabs/connect/Connect.js
mobile/src/tabs/discover/Discover.js
mobile/src/tabs/home/Home.js

Should fix issues we're seeing on TestFlight builds around caching

Add fetch policies to improve data loading from server

---

mobile/package.json
mobile/src/live/LiveButton.js
mobile/src/live/LiveButton.tests.js
mobile/src/live/getLiveStream.graphql
mobile/yarn.lock

fix the `getLiveStream` query so that the LiveButton shows back up

---

README.md
mobile/src/content-feed/index.js

Added Inline Documentation

---

mobile/src/ui/VideoPlayer/VideoPlayer.stories.js
mobile/src/ui/VideoPlayer/VideoPlayer.tests.js
mobile/src/ui/VideoPlayer/__snapshots__/VideoPlayer.tests.js.snap

Add stories and tests for VideoPlayer overlay

---

packages/apollos-church-api/src/data/auth/data-source.js

Import Request class from ApolloEnv

---

.travis.yml
package.json
packages/apollos-church-api/package.json
packages/babel-preset-apollos/package.json

Fix now deploys

---

packages/apollos-church-api/__mocks__/apollo-server-env.js
packages/apollos-church-api/src/data/bible/_tests_/__snapshots__/resolver.tests.js.snap
packages/apollos-church-api/src/data/bible/_tests_/resolver.tests.js
packages/apollos-church-api/src/data/bible/data-source.js
packages/apollos-church-api/src/data/bible/resolver.js
packages/apollos-church-api/src/data/bible/schema.js
packages/apollos-church-api/src/data/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
packages/apollos-church-api/src/data/content-items/__tests__/resolvers.tests.js
packages/apollos-church-api/src/data/content-items/index.js
packages/apolloschurchapp/src/ui/Scripture/Item.js
packages/apolloschurchapp/src/ui/Scripture/Scripture.stories.js
packages/apolloschurchapp/src/ui/Scripture/Scripture.tests.js
packages/apolloschurchapp/src/ui/Scripture/getScripture.js
packages/apolloschurchapp/src/ui/Scripture/index.js

fixed up the tests that my PR broke.

---

packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj

Fix missing bracket in xcodeproj file

---

packages/apolloschurchapp/src/store/index.js

Fixes test code left in store/index

---

README.md
package.json
scripts/change-log/generate-git-log.sh

Fix release script so CHANGLOG.md users proper version

---

.travis.yml
package.json
yarn.lock

Sets up [Apollo Engine](https://engine.apollographql.com/service/apollos-church-api/explorer)
Will allow us to view analytics over our Api. Includes performance data and usage data, does _not_ include ability to cache parts of our schema until we add the `ApolloEngine` package.

Apollo engine setup

---

CHANGELOG.md
lerna.json
package.json
packages/apollos-church-api/package.json
packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json
scripts/change-log/append-change-log.js

Release v0.6.0

---

packages/apollos-church-api/src/connectors/cloudinary.js
packages/apollos-church-api/src/data/people/__tests__/__snapshots__/resolvers.test.js.snap

Fixes profile image in Cloudinary

---

.github/PULL_REQUEST_TEMPLATE.md

See file changed tab for new PR template

Implement new PR template to encourage better code reviews

---

packages/apolloschurchapp/android/app/build.gradle

It is a potential fix for our Android distribution fails.
N.A.
Look to AppCenter. But this change is needed either way.
N.A.
**Manual QA**

Updated bundle id for android

---

packages/apollos-church-api/src/config.js
packages/apollos-church-api/src/data/content-channels/__tests__/resolvers.tests.js
packages/apollos-church-api/src/data/content-channels/data-source.js
packages/apollos-church-api/src/data/content-items/__tests__/resolvers.tests.js
packages/apollos-church-api/src/data/content-items/data-source.js
packages/apollos-church-api/src/server.js
packages/apollos-config/src/__tests__/__snapshots__/js-load.tests.js.snap
packages/apollos-config/src/__tests__/__snapshots__/yaml-load.tests.js.snap
packages/apollos-config/src/index.js

Allows the user to configure content channels used in the config.yml file.
n/a
- Boot the API and the App
- Remove an id from the `config.yml` under `ROCK_MAPPINGS -> DISCOVER_CONTENT_CHANNEL_IDS` and make sure the associated disappears from the home feed.
- Remove an id from the `config.yml` under `ROCK_MAPPINGS -> FEED_CONTENT_CHANNEL_IDS` and make sure the associated disappears from the category feed.
Updated existing tests to use new functionality 
**Manual QA**

Add Content Channels Support to Apollos Config

---

packages/apollos-church-api/package.json
packages/apollos-church-api/src/config.js
packages/apollos-church-api/src/connectors/__tests__/cloudinary.tests.js
packages/apollos-church-api/src/connectors/cloudinary.js
packages/apollos-church-api/src/connectors/rock/rock-constants.js
packages/apollos-church-api/src/data/analytics/__tests__/data-source.tests.js
packages/apollos-church-api/src/data/analytics/data-source.js
packages/apollos-church-api/src/data/auth/__tests__/index.tests.js
packages/apollos-church-api/src/data/auth/data-source.js
packages/apollos-church-api/src/data/bible/data-source.js
packages/apollos-church-api/src/data/content-channels/__tests__/model.tests.js
packages/apollos-church-api/src/data/content-channels/__tests__/resolvers.tests.js
packages/apollos-church-api/src/data/content-channels/data-source.js
packages/apollos-church-api/src/data/content-items/__tests__/data-source.tests.js
packages/apollos-church-api/src/data/content-items/__tests__/resolvers.tests.js
packages/apollos-church-api/src/data/content-items/data-source.js
packages/apollos-church-api/src/data/content-items/index.js
packages/apollos-church-api/src/data/family/__tests__/data-source.tests.js
packages/apollos-church-api/src/data/family/__tests__/schema.tests.js
packages/apollos-church-api/src/data/family/data-source.js
packages/apollos-church-api/src/data/interactions/__tests__/resolvers.tests.js
packages/apollos-church-api/src/data/interactions/data-source.js
packages/apollos-church-api/src/data/media/index.js
packages/apollos-church-api/src/data/people/__tests__/data-source.tests.js
packages/apollos-church-api/src/data/people/__tests__/resolvers.test.js
packages/apollos-church-api/src/data/people/data-source.js
packages/apollos-config/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-rock-apollo-data-source/src/index.js
yarn.lock

Renames @apolloschurch to @apollosproject

---

.dockerignore

Getting the following error in travis
```
> Error! EMFILE: too many open files, open '/home/travis/build/ApollosProject/apollos-prototype/packages/apollos-ui-kit/node_modules/@storybook/core/node_modules/core-js/es6/weak-set.js'
```
We need to exclude the ui-kit folder and the node_modules for all newly added packages. 
**Manual QA**

Fixed now deploys

---

packages/apolloschurchapp/.env.production

Fix deploys

---

Dockerfile
lerna.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-people/package.json
packages/apollos-data-connector-rock-auth/package.json
packages/apollos-data-connector-rock-content/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.0 pre1

---

lerna.json
package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-people/package.json
packages/apollos-data-connector-rock-auth/package.json
packages/apollos-data-connector-rock-content/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.0 alpha.2

---

packages/apollos-church-api/package.json
yarn.lock

Updates nodemon to remove flatmap-stream dep

---

.gitignore
packages/apollos-ui-kit/src/theme/mixins.js

This fixes a bug in theme mixins where we weren't properly inheriting from context. Pretty simple fix and change, appears to not affect snapshots, so yeah! (Which, I guess also means we didn't have this in our test covewrage, soboo1)
**Manual QA**

Fix theme mixins

---

packages/apolloschurchapp/package.json
yarn.lock

Updates nodemon in client

---

lerna.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-people/package.json
packages/apollos-data-connector-rock-auth/package.json
packages/apollos-data-connector-rock-content/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

v0.8.0-alpha.3

---

lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-people/package.json
packages/apollos-data-connector-rock-actions/package.json
packages/apollos-data-connector-rock-auth/package.json
packages/apollos-data-connector-rock-content/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.0 alpha.4

---

lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-people/README.md
packages/apollos-data-connector-rock-actions/README.md
packages/apollos-data-connector-rock-auth/README.md
packages/apollos-data-connector-rock-content/README.md
packages/apollos-data-connector-rock/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

 Release v0.8.0-alpha.5

---

lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.0-alpha.6

---

packages/apollos-church-api/config.yml
packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
packages/apollos-data-connector-rock/src/content-items/data-source.js
yarn.lock

This PR does two things
1. Rock expects all dates passed to it to be in the timezone of the rock instance (which was Eastern, for the ChristFellowship folks, and is the same for ApollosRock). If you pass it ISO8601 strings (which we do when filtering) it ignores the timezone of the string. So if you send it UTC 5:00PM, it interprets it as EST 5:00PM. This was leading to content items not appearing or disappearing in the app at the correct time.
This PR fixes that behavior, and allows users to set a timezone in the app, and all dates will be offset by the appropriate offset so as to match the timezone of Rock.
2. This app sets up the `CONTENT_LIVE` filter as a property of the ContentItem data source, so it can be overridden by implementations as needed. That way churches that need to …

Fixes timezone of dates sent to rock when filtering content items

---

lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json
yarn.lock

Release v0.8.0 alpha.7

---

packages/apollos-church-api/src/server.js
packages/apollos-data-schema/src/index.js
packages/apolloschurchapp/.env.production
packages/apolloschurchapp/src/client/httpLink.js

This will add a cache layer to all our queries and a corresponding Fastly CDN route to handle them.
None.
Run queries using the following types and make sure they aren't cached:
None.
**Manual QA**

Adds Fastly CDN and Data Caching

---

package.json

Adds ability to run yarn ios and yarn android from project root

---

packages/apolloschurchapp/.env.production

The url in `.env.production` was using `https`, but the cert was invalid. Based on some fastly documentation, @redreceipt and I figured out what the URL should be and updated it. 
https://docs.fastly.com/guides/tls/setting-up-free-tls
**Manual QA**

Uses proper CDN url in Prod

---

packages/apollos-server-core/src/index.js
packages/apollos-server-core/src/utils/__tests__/index.tests.js
packages/apollos-server-core/src/utils/index.js

Adds a utility function to merge a data-connector and some new resolvers. Helps safely ensure that no stray resolvers are overridden and that all non-overriden resolvers are included. 
n/a
Would recommend running test suite. This code is not currently used by the app.
Tests over new utility function. 
**Manual QA**

Adds deep schema merge tool

---

lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-twilio/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-passes/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.0 alpha.8

---

.dockerignore

Don't package up ui-passes into server docker image

---

packages/apollos-ui-kit/src/index.js

There was a typo in ProgressiveImage causing it to not be exported!
**Manual QA**

Fixes ProgressiveImage Typo

---

packages/apolloschurchapp/src/store/index.js

fixed warning

---

packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/content-items/data-source.js

Fixes warnings lie this one.
Clone PR, restore `content-items/data-source.js` to state prior to this PR. Run tests and watch them fail ;) 
Tests over datasource are included.
**Manual QA**

Fixes filter error when content item has no images and no parents with images

---

lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-twilio/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-passes/package.json
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.0-alpha.9

---

packages/apollos-data-connector-onesignal/README.md

Adds Readme for OneSignal package

---

packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/resolvers.test.js.snap
packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/people/__tests__/resolvers.test.js
packages/apollos-data-connector-rock/src/people/data-source.js
packages/apollos-data-connector-rock/src/people/resolver.js
packages/apollos-data-schema/src/index.js

This endpoint (ported from Highliner) leaks people data and is not used in the current app. This PR removes it.
n/a
1. Clone this PR.
2. Boot up the API.
3. You should not see the `person` endpoint on the root of the schema in graphiql. 
Removed existing tests over this endpoint.
**Manual QA**

Removes People (by email) Query

---

packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/people/data-source.js

@IsaacHardy Needed this for one of his PR's. This is also a method that other rock functionality will also probably need, given the prevalence of AliasID in the codebase. 
n/a
Tests are written. There is currently no end-user code that use's this functionality, so read over tests.
DataSource tests over dataSource.
**Manual QA**

Adds `getPersonByAliasId` method on Person dataSource

---

packages/apolloschurchapp/src/user-settings/Locations/campusChange.js
packages/apolloschurchapp/src/user-settings/Locations/index.js

User profile wasn't updated until a refresh
None
Login and change your location, your profile should be updated.
None
**Manual QA**

Added Update to Location Mutation

---

CHANGELOG.md
lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-twilio/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-auth/package.json
packages/apollos-ui-htmlview/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-passes/package.json
packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.1

---

packages/apollos-ui-auth/src/ProtectedRoute.js
packages/apollos-ui-auth/src/ProtectedRoute.tests.js
packages/apollos-ui-auth/src/index.js
packages/apolloschurchapp/src/auth/index.js
packages/apolloschurchapp/src/index.js
packages/apolloschurchapp/src/onboarding/index.js
packages/apolloschurchapp/src/ui/Onboarding/index.js
packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskNameConnected.js

Adds routing from Auth -> Onboarding -> Home
n/a
1. Signout of the app.
2. Refresh the app, and login
3. Navigate through onboarding
4. You should end up on the home screen.
**Manual QA**

Adds routing from Auth -> Onboarding -> Home

---

packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.js
packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.tests.js
packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap

New users or user's without a birth date were previously unable to select a date. The app would crash when they tapped on the date picker, and the field itself would display "Invalid Date". I believe I might have caused this issue when I tried to clean up some of the date passing logic.
1. Open the app and register as a new user.
2. Progress through onboarding.
- you should see todays date as your birth date
- you should be able to tap the date to select your birthdate
Snapshot tests
**Manual QA**

Fixes date picker being unusable for users with null dates

---

packages/apolloschurchapp/package.json
yarn.lock

This lets you use `handleChange` and `handleBlur` according to their simple implementation: https://jaredpalmer.com/formik/docs/guides/react-native
Currently, you get a warning and it doesn't work:

Upgrades Formik

---

packages/apolloschurchapp/src/Providers.js

removes a warning from the onboarding flow. It was a placeholder for an Analytics tracker.
None
Boot up, go through onboarding, confirm no warning.
None
**Manual QA**

Removes Warning from Onboarding

---

packages/apollos-ui-kit/src/CardTile/CardTile.tests.js
packages/apollos-ui-kit/src/CardTile/__snapshots__/CardTile.tests.js.snap

Fixes a test that was producing a date representation that changes every year.
`yarn test`
**Manual QA**

Fixed Card Tile Test

---

CHANGELOG.md
lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-twilio/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-analytics/package.json
packages/apollos-ui-auth/package.json
packages/apollos-ui-htmlview/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-passes/package.json
packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release 0.8.3

---

packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
packages/apolloschurchapp/android/settings.gradle
packages/apolloschurchapp/jest.setup.js
packages/apolloschurchapp/package.json
packages/apolloschurchapp/src/ui/WebBrowser/Browser.android.js
packages/apolloschurchapp/src/ui/WebBrowser/Browser.ios.js
yarn.lock

Removes `react-native-custom-tabs`
@vinnyjth said we don't need it. I believe him.
No custom tabs...I guess.
Boot up android and use the in app web browser.
None.
**Manual QA**

Removes Custom Tabs

---

packages/apollos-data-connector-rock/README.md

Update Apollos Data Rock README.md

---

CHANGELOG.md
lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-twilio/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-analytics/package.json
packages/apollos-ui-auth/package.json
packages/apollos-ui-htmlview/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-passes/package.json
packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.4

---

CHANGELOG.md
lerna.json
packages/apollos-apollo-server-env-mock/package.json
packages/apollos-church-api/package.json
packages/apollos-config/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-cloudinary/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-connector-twilio/package.json
packages/apollos-data-schema/package.json
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-server-core/package.json
packages/apollos-ui-analytics/package.json
packages/apollos-ui-auth/package.json
packages/apollos-ui-htmlview/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-onboarding/package.json
packages/apollos-ui-passes/package.json
packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
packages/apolloschurchapp/package.json
packages/babel-preset-apollos/package.json

Release v0.8.5

---

packages/apollos-church-api/apollos.json
packages/apollos-church-api/package.json
packages/apolloschurchapp/apollos.json
packages/apolloschurchapp/package.json
scripts/update-apollos-version.js

This PR creates an `apollos.json` file. This file only exists so that the upgrade tool has something to work with when assuming the user's current version and current environment. With this file, we can simplify the code required to complete the process of minimizing the args that you need to pass to the upgrade tool. 
When you run the upgrade tool, it will look at this file to determine it's context (api or client) and then look at the version to find the "current version". When the upgrade tool is run, this file will automatically be updated to reference the new current version (the end user will never have to touch this file). 
I also added steps to the release process so that this file stays in sync with the current package version.
**Manual QA** …

Adds Apollos.json to help improve upgrade tool.

---

packages/apolloschurchapp/appcenter-pre-build.sh

Fix appcenter

---

.travis.yml

Travis deploy script arg can only take a single command

---

packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/people/data-source.js

GetPersonById should return Photo

---

packages/apolloschurchapp/src/ui/LikeButton/index.js
packages/apolloschurchapp/src/ui/LikeButton/updateLikeEntity.js

We weren't updating the `likeCount` cache when something was liked. This fixes that.
Don't think any.
Like/Unlike something and then make sure it was updated in the home feed.
None.
**Manual QA**

Updates Liked Count on Home Feed

---

packages/apollos-data-connector-bible/src/data-source.js

Fixes bible.api not handling both data and data.passages

---

.travis.yml
packages/apollos-ui-kit/docs/buildDocs.sh

1. Travis script is broken because `git commit` is returning 1 if nothing has changed.
2. Nothing is showing up in UI-Kit section because the script is not generating the sidebar keys properly. This fixes those things.
None.
🤞
None.
**Manual QA**

Fixes Docs Sidebar Table of Contents

---

packages/apolloschurchapp/android/app/build.gradle
packages/apolloschurchapp/android/app/src/main/AndroidManifest.xml

Last week, Google Maps Services started this [policy](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library)
```
If you are using com.google.android.gms:play-services-maps:16.0.0 or below and your app is targeting API level 28 (Android 9.0) or above, you must include the following declaration within the <application> element of AndroidManifest.xml.
```
This PR updates the package version and removes an unneeded comment in that file.
N/A
Boot up an android sim and make sure mapviews aren't crashing the app.
N/A
**Manual QA**

Fixes Google Maps Issue

---

packages/apollos-ui-analytics/package.json
packages/apolloschurchapp/package.json
yarn.lock

Updates `react-native-device-info` package to version 2.1.2 and fixes Android builds.
None.
QA both iOS and Android broadly and make sure analytics still works.
None.
**Manual QA**

Updates Device Info Package

---

packages/apollos-ui-passes/src/index.js

Fixes not being able to close the check in screen.
Seems like the `withNavigation` from ui-kit doesn't ever call in the "right" version of the navigation context. This might be fixed in a newer version of react navigation.
1. Open the check in screen.
2. Close the check in screen.
n/a
**Manual QA**

Fixes not being able to close the check in screen

---

packages/apollos-church-api/config.yml
packages/apollos-church-api/src/data/index.js
packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js
packages/apollos-data-connector-rock/src/content-items/data-source.js
packages/apollos-data-connector-rock/src/content-items/resolver.js
packages/apollos-data-connector-rock/src/features/index.js
packages/apollos-data-connector-rock/src/index.js
packages/apollos-data-schema/src/index.js

This PR adds some minimal groundwork so I can get started on the Features work. It adds the implementation we will be using to fork off, plus a placeholder dataSource / resolver for a `WeekendContentItem`.
n/a
n/a
n/a
**Manual QA**

Adds Features boilerplate schema/resolvers/datasource

---

packages/apolloschurchapp/src/ui/Onboarding/Onboarding.tests.js
packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap

Adds test coverage for the Onboarding sequence
None
`yarn test`
One snapshot test
**Manual QA**

Adds Onboarding Test Coverage

---

packages/apolloschurchapp/android/app/build.gradle

This PR updates the app so that it will successfully build 64-bit versions, thereby allowing us to continue to update in the Google Play store after August 1st, 2019.
The changes made were done so after consideration from a couple of articles. I'll list them here for reference:
- https://medium.com/@andriidrozdov/reactnative-and-android-64-bit-new-google-play-market-rules-what-to-do-584b067d6f1a
- https://developer.android.com/distribute/best-practices/develop/64-bit
N/A
Build this and test on an Android device to make sure it still works. 
Open the project in Android Studio.
Run *Build > Analyze APK...* and choose to run the *app > build > outputs > apk > debug > app-debug.apk* file.
When this finishes, look in the *lib* folder.
You should see the following 4 folders: `x86-64`, `x86`, …

Update to build 64-bit Android versions

---

packages/apollos-ui-media-player/src/MediaPlayer/FullscreenControls.js
packages/apollos-ui-media-player/src/MediaPlayer/FullscreenPlayer.js
packages/apollos-ui-media-player/src/MediaPlayer/FullscreenPlayer.tests.js
packages/apollos-ui-media-player/src/MediaPlayer/VideoWindow.js
packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
packages/apollos-ui-media-player/src/MediaPlayer/index.js
packages/apollos-ui-media-player/src/index.js

Adds some component prop customization to MediaPlayer so that we can add a `YouTube` player as per Willow
None really besides adding additional component API
Updated snapshot tests. Code is tested in the youtube branch #859 
**Manual QA**

Allow for custom VideoWindow component and disabling of toggle controls on MediaPlayer

---

packages/apollos-rock-apollo-data-source/src/__tests__/__snapshots__/request-builder.tests.js.snap
packages/apollos-rock-apollo-data-source/src/__tests__/request-builder.tests.js
packages/apollos-rock-apollo-data-source/src/request-builder.js

Simply fixes the request builder so it doesn't add `filter=` to a URL if there are no filters.
None.
None.
Two snaps.
**Manual QA**

Adds Safety Checks to Request Filters

---

packages/apollos-rock-apollo-data-source/src/__tests__/utils.tests.js
packages/apollos-rock-apollo-data-source/src/index.js
packages/apollos-rock-apollo-data-source/src/utils.js

The way Key/Values are sent over by Rock is .... odd. This utility helps mitigate the complexity and adds a utility to parse the KeyValue strings into Javascript objects.
This does _not_ handle values that include `|`s or `^`s. I believe those are already handled by Rock (it specifically encodes those characters) 
Look at tests.
Tests over new utility. 
**Manual QA**

Adds utility to handle rock key/value attribute

---

packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
packages/apollos-ui-kit/src/Chip/Chip.stories.js
packages/apollos-ui-kit/src/Chip/Chip.tests.js
packages/apollos-ui-kit/src/Chip/__snapshots__/Chip.tests.js.snap
packages/apollos-ui-kit/src/Chip/index.js
packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap

These are some small and subtle padding changes to `Chip` from the new design work for Apollos core. This PR is needed for #867 
Updates `Chip` and any related snapshots.
N/A
Open storybook, check the stories for `Chip`
All the snaps
**Manual QA**

Updates core Chip component styles

---

packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
packages/apollos-data-connector-rock/src/features/data-source.js

Fixes action list features having the same id

---

packages/apollos-config/src/__tests__/__snapshots__/js-load.tests.js.snap
packages/apollos-config/src/__tests__/js-load.tests.js
packages/apollos-config/src/__tests__/yaml-load.tests.js

Adds test coverage
**Manual QA**

Adds 100% Test Coverage to Config Package

---

packages/apolloschurchapp/src/utils/content/__tests__/share.tests.js

Adds 100% Coverage to Share Function

---

packages/apollos-data-connector-rock/src/content-items/data-source.js

here you go @vinnyjth :)
**Manual QA**

Adds Token Check

---

packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
packages/apollos-ui-passes/src/PassView/index.js

Align ui-passes image to the right

---

packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/content-items/data-source.js

This simplifies how we define features in Rock and gives us the ability to mix the order.
None.
Run this:
```graphql
{
userFeed {
edges {
node {
... on WeekendContentItem {
features {
__typename
... on TextFeature {
body
}
... on ScriptureFeature {
scriptures {
reference
}
}
}
}
}
}
}
}
```
None.
**Manual QA**

Simplifies Feature Content Sources

---

packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js

This PR adds sharing to the scripture feature.
No trade offs really. The scripture isn't formatted as nicely as on the components, but I'm not sure that's possible when sharing.
Find a content item where the sharing feature is being used and make sure sharing works. 
None.
- [n/a] Closes [tag-issues-here]
**Manual QA**

Adds Sharing to the Scripture Feature

---

packages/apolloschurchapp/src/user-settings/index.js

Fixes not being able to reach the "logout" button on the settings screen, because the view didn't scroll.
Chose to make the view scroll instead of decreasing the amount of content. 
Visit the settings screen in an SE simulator or an Android device with a smaller screen. You'll be able to reach the settings button by scrolling
**Manual QA**

Fixes not being able to reach logout button on small screen sizes

---

packages/apolloschurchapp/package.json

Removes Duplicate Storybook Dependency

---

packages/apollos-church-api/wallet-passes/checkin.pass/pass.json

Changes the label color on the Passes from black (default) to white. 
1. Click "check in" on your user profile.
2. The pass label color should be white instead of black.
n/a
**Manual QA**

Fixes PassKit label color

---

packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
packages/apolloschurchapp/src/ui/Onboarding/index.js

Adds grey backgrounds back to onboarding. Does the same thing I did in Willow to achieve a full screen background. 
n/a
Open onboarding. You should see a `BackgroundView` as a background instead of the grey RN navigation background.
updated snaps
**Manual QA**

Adds BackgroundView back to onboarding

---

package.json
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj

Fixes RNCAsyncStorage build issue

---

packages/apolloschurchapp/src/content-single/HorizontalContentFeed/index.js
packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js

None, I think
Open content singles that have children or sibling content, click on them , etc.
None. No snapshot changes either 🤔
**Manual QA**

Use `<HorizontalContentCard />` on Content Item children+siblings

---

packages/apolloschurchapp/src/tabs/discover/Discover.js

Fixes Discover tab rendering on tablets.
This was a super weird fix. I couldn't, for the life of me, get flex/styling to completely eliminate the problem. I was about to reach out for ideas from others when I decided to check for bugs/issues with `FlatList`. When scrolling past the props documentation I found `numColumns`. This isn't a required prop nor is it platform specific nor does it have a default! Fix? `numColumns={1}` Weird... I know 🙃 
None.
To test this PR on iOS you will have to open xcode and set the `Deployment Info` to `Universal` or `Ipad`. This is temporary, do not commit the files that this change creates. Now you can build for the iPad of your choice to test this PR. Android studio has a few Android tablets to pick from (not that there is anyone in the world who uses an …

Fixes Discover tab rendering on tablets

---

packages/apollos-ui-kit/src/ModalView/ModalViewHeader.js
packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap

The modal header icons were hard to see, this makes them pearly white
None.
Open up a piece of content that was previously hard to see the "X" in the close button.
None.
**Manual QA**

Improves Header Contrast

---

packages/apolloschurchapp/src/Providers.js

Fixes calling removed function

---

packages/apollos-ui-notifications/package.json
packages/apolloschurchapp/appcenter-post-clone.sh
packages/apolloschurchapp/appcenter-pre-build.sh
packages/apolloschurchapp/ios/Podfile.lock
packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
packages/apolloschurchapp/package.json
yarn.lock

Fixes configuration of react-native-onesignal
n/a
have @burkeshartsis build this.
n/a
**Manual QA**

Fixes onesignal pod not installing

---

packages/apollos-ui-auth/src/Password/Login/Form.js
packages/apollos-ui-auth/src/Password/Signup/Form.js

Fixes Lint Error

---

packages/apollos-church-api/local.graphql
packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/data-source.test.js.snap
packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/resolver.test.js.snap
packages/apollos-data-connector-rock/src/groups/__tests__/data-source.test.js
packages/apollos-data-connector-rock/src/groups/__tests__/resolver.test.js
packages/apollos-data-connector-rock/src/groups/data-source.js
packages/apollos-data-connector-rock/src/groups/resolver.js
packages/apollos-data-schema/src/index.js

This adds support to get all leaders of a group, not just the first in the list.
Deprecated the old field.
```
{
currentUser {
profile {
groups {
leaders {
firstName
}
}
}
}
}
```
Modified a couple
**Manual QA**

Add Multiple Group Leader Support

---

packages/apollos-data-connector-algolia-search/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-rock/src/campuses/data-source.js
packages/apollos-data-connector-rock/src/content-channels/data-source.js
packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/content-items/data-source.js
packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/data-source.test.js.snap
packages/apollos-data-connector-rock/src/events/data-source.js
packages/apollos-data-connector-rock/src/rock-constants/__tests__/__snapshots__/rock-constants.tests.js.snap
packages/apollos-rock-apollo-data-source/package.json
packages/apollos-rock-apollo-data-source/src/__tests__/__snapshots__/request-builder.tests.js.snap
packages/apollos-rock-apollo-data-source/src/request-builder.js
yarn.lock

Previous override of the `ttl` used the wrong syntax. That feature isn't well documented, so I had to look at some examples in the Apollos codebase to make sure I had things right. 
https://github.com/apollographql/apollo-server/blob/d5015f4ea00cadb2a74b09956344e6f65c084629/packages/apollo-datasource-rest/src/RESTDataSource.ts#L253
Some requests might take a bit longer than expected to return "new" results. Most should be capped at 60 seconds of old results, and the cache can be wiped by restarting the server.
n/a
Updated tests.
**Manual QA**

Adds TTLs throughout the app to speed up repeat Rock requests

---

packages/apollos-church-api/local.graphql
packages/apollos-data-schema/src/index.js

I'm amazed that when I removed firstName as a required attribute, I forgot to remove last name.
**Manual QA**

Removes last name as a required attribute

---

packages/apollos-data-connector-rock/src/content-items/data-source.js
packages/apollos-data-connector-rock/src/content-items/resolver.js

This fixes pulling `summary` field correctly
None
Look through content items with summaries and no content
None
**Manual QA**

Fixes Summary Field

---

packages/apollos-church-api/scripts/generateLocalSchema.sh

This will publish the current schema to Engine when we check for breaking changes in Travis.
**Manual QA**

Publish Schema to Engine

---

packages/apollos-data-connector-rock/src/content-items/data-source.js
packages/apollos-rock-apollo-data-source/src/utils.js

This safely decodes text from the feature key/value pairs.
None.
```
{
userFeed {
edges {
node {
... on ContentItem {
__typename
title
... on WeekendContentItem {
features {
... on TextFeature {
body
}
}
}
}
}
}
}
}
```
The "Spur One Another" sermon has an example of one.
None.
**Manual QA**

Decodes Feature Text

---

packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.tests.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap
packages/apolloschurchapp/ios/Podfile.lock

This doesn't change any perceived functionality, it simply gives all available information to the `LocationFinder` component to make the best decision possible for the UI. `campus` wasn't being passed down at all if the location permission hadn't been granted yet. This passes it down regardless and then bases the presence of the campus card on the "Next" button instead of the campus being passed in.
For core, this changes nothing but for partners, it allows them to use the campus information if they need it.
Removed `buttonDisabled` prop from `LocationFinder`. It wasn't being used anyway.
- Try onboarding with no campus set
- Try it with a campus already set with no location permission
- Try it with a campus and the permission already set
None.
**Manual QA**
**Code Review: Questions to …

Refactors Locations in Onboarding

---

packages/apollos-church-api/local.graphql
packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/data-source.test.js.snap
packages/apollos-data-connector-rock/src/events/__tests__/data-source.test.js
packages/apollos-data-connector-rock/src/events/data-source.js
packages/apollos-data-connector-rock/src/events/resolver.js
packages/apollos-data-schema/src/index.js
packages/apolloschurchapp/src/event/Event.js
packages/apolloschurchapp/src/event/EventConnected.tests.js
packages/apolloschurchapp/src/event/__snapshots__/Event.tests.js.snap
packages/apolloschurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
packages/apolloschurchapp/src/event/getEvent.js

Descriptions from EventItems now show up in the app, if provided.
**Manual QA**

Adds event descriptions

---

packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js

Removes a check on the close button that checked if the player was playing or not. Now if you click close it closes immediately.
N/A
Check the stories
There were no previous tests for this component.
**Manual QA**

Fixes miniplayer close button

---

packages/apolloschurchapp/src/ui/WebBrowser/Browser.js

Just makes the auth token query `network-only`
None
Click the "InAppBrowser" link in the test panel multiple times, should log in every time.
None
**Manual QA**

Removes Caching of Auth Tokens

---

packages/apollos-data-connector-rock/src/groups/data-source.js

Fixes Group members function

---

packages/apollos-ui-analytics/jest.setup.js
packages/apollos-ui-analytics/package.json
packages/apollos-ui-analytics/src/Analytics.tests.js
packages/apollos-ui-analytics/src/Provider.js
packages/apolloschurchapp/ios/Podfile.lock
packages/apolloschurchapp/jest.setup.js
packages/apolloschurchapp/package.json
yarn.lock

Needed for willow :) 
2. Open a content item
3. Ensure the app doesn't crash 😘 
**Manual QA**

Upgrade react native device info

---

README.md

This PR recommends to any contributor to add `eslint.validate` to their eslint configuration. This allows eslint to validate your Javascript. 
n.a.
n.a.
n.a.
**Manual QA**

Adds additional ESLint recommendation to readme

---

packages/apolloschurchapp/src/user-settings/Locations/MapView.js

This one is as simple as it sounds. Just adds the MediaPlayerSpacer component to the Locations screen so that the Media Player doesn't sit on top of the action button on the Locations Screen when the Media Player is open.
1. Play something on the media player
2. Minimize the media player
3. Open the location finder from the profile settings screen. 
You should also take a look at the Locations screen without the media player open to ensure all is well.
||IOS|Android|
|---|---|---|
|Open|<img width="569" alt="Screen Shot 2019-10-25 at 1 48 39 PM" src="https://user-images.githubusercontent.com/29125070/67593277-d3c5f400-f72f-11e9-85b6-3c0bfb6a2570.png">|<img width="545" alt="Screen Shot 2019-10-25 at 2 09 19 PM" src="https://user-images.githubusercontent.com/29125070/67593892-28b63a00-f731-1 …

Location Screen Media Player Spacing

---

packages/apollos-data-connector-twilio/src/data-source.js

Fixes twilio sid logged on every request

---

packages/apollos-data-connector-algolia-search/src/resolver.js
packages/apollos-data-connector-rock/src/followings/data-source.js
packages/apollos-data-connector-rock/src/followings/resolver.js
packages/apollos-server-core/__mocks__/graphql-parse-resolve-info.js
packages/apollos-server-core/package.json
packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
packages/apollos-server-core/src/node/__tests__/model.js
packages/apollos-server-core/src/node/model.js
packages/apollos-server-core/src/node/resolver.js
scripts/watch.js
yarn.lock

If we are fetching a piece of data that implements `node` using `Node.get()` we should first check to see if we are asking for more than just `node.id` and `node.__typename`. If we aren't, we should send back the data we already have rather than fetching data from Rock.
1. Boot the API. 
2. Run the following query, you should see "0 requests" in the API console. You should also see the `someId`, `__typename`, and `id` field properly resolve. 
```
query searchResults {
search(query: "Jesus") {
edges {
title
summary
coverImage {
name
sources {
uri
}
}
cursor
node {
... on ContentItem {
someId:id
__typename
id
}
... on UniversalContentItem {
id
}
}
}
}
}
```
3. Now run the following query. See that we added `title` to one of the node fields. You will see that requests to Rock are now being …

Grants `Node.get` the ability to shortcut fetching the data from Rock. 

---

packages/apollos-ui-kit/src/DefaultCard/DefaultCard.stories.js
packages/apollos-ui-kit/src/DefaultCard/DefaultCard.tests.js
packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
packages/apollos-ui-kit/src/DefaultCard/index.js
packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.stories.js
packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.tests.js
packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
packages/apollos-ui-kit/src/FeaturedCard/index.js
packages/apollos-ui-kit/src/HighlightCard/HighlightCard.stories.js
packages/apollos-ui-kit/src/HighlightCard/HighlightCard.tests.js
packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
packages/apollos-ui-kit/src/HighlightCard/index.js
packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.stories.js
packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.tests.js
packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.stories.js
packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.tests.js
packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
packages/apolloschurchapp/src/content-single/HorizontalContentFeed/__snapshots__/HorizontalContentFeed.tests.js.snap
packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap

This card makes the `LikeIcon` optional on all cards so that it doesn't render anything unless it's `true/false`. This preserves the cards previous functionality while allowing for query perf improvements by not rendering an icon at all if we don't want to.
Another PR will follow to remove the `LikeIcon` from cards in the app.
None.
Check the stories.
100% test coverage 💪 
**Manual QA**

Makes like icon optional on cards

---

packages/apollos-church-api/config.yml
packages/apollos-server-core/package.json
packages/apollos-server-core/src/index.js
yarn.lock

Forces auth on the jobs board located at `${SERVER_ADDRESS}/admin/queues`. Now whenever you are accessing that address, it will be necessary to provide the correct username and password. These can be set in the .env file.
1. Start your server
2. Proceed to localhost:4000/admin/queues
3. You should be prompted for username and password
4. Enter `username` and `password`
5. You should be successfully logged in
**Manual QA**

Jobs Board Auth

---

packages/apollos-data-connector-rock/src/auth/data-source.js

We neglected to include an enhancement that would ensure that `getCurrentPerson` would only get called if it was likely to succeed. 
**Manual QA**

Only try to get the current person if you have a rock cookie

---

packages/apollos-data-schema/src/index.js

Ensures user feed is cachables

---

.mergify.yml

Mergify Will Delete Branch

---

packages/apollos-church-api/local.graphql
packages/apolloschurchapp/src/client/index.js

This gives us client info in the request headers, useful anywhere, but especially in Apollo Engine.
None.
Boot both iOS and Android and inspect the requests.
None.
**Manual QA**

Adds Client Info in Request Headers

---

packages/apollos-ui-kit/src/CampusCard/index.js

Adds a check to the CampusCard component that ensures that all images passed to it are indeed valid.
This means it checks that the array exists, that none of the objects in the array are equal to `null`, and that the `uri` key in the objects is not null.
The change is intended to fix an issue that occurs in the New Spring app, but the protection should be added to core, thus this PR!
**Manual QA**

Check for Valid Images When Rendering Campus Cards.

---

packages/apollos-ui-auth/src/Password/index.js
packages/apollos-ui-auth/src/SMS/Verification.js
packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap

This changes the Auth `BackButtons` to use `action.secondary` to be more easily customizable.
Using `action.seconardy` also highlights the `primary` cta at the bottom.
Logout check through auth.
N/A
**Manual QA**

Fixes auth back button color

---

packages/apolloschurchapp/src/ui/ContentCardConnected/ContentCardConnected.js

This changes the default of `labelText` from `null` to `''`. Both are falsy so the label won't show up, but insures that `labelText` inherits from the string prototype so functions (like `replace`) won't error out.
TL;DR more consistent typing :)
None.
🤷‍♂️
None.
**Manual QA**

Improves Content Label Default Type

---

packages/apollos-ui-kit/src/Card/ErrorCard/ErrorCard.stories.js
packages/apollos-ui-kit/src/Card/ErrorCard/ErrorCard.tests.js
packages/apollos-ui-kit/src/Card/ErrorCard/__snapshots__/ErrorCard.tests.js.snap
packages/apollos-ui-kit/src/Card/ErrorCard/index.js
packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap

This removes the technical error message by default and makes the card a little prettier.
None.
Pull up the story.
Added a couple snaps.
**Manual QA**

Improves the Error Card

---

packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/auth/data-source.js

This field slipped in by mistake in an unrelated PR. This PR removes the field, and adds tests to reduce the chances of this happening again.
1. Logout
2. Create a new profile (using a new SMS number or via email)
3. Your new profile should be created without errors.
Tests over new functionality
**Manual QA**

Remove willow specific field when creating new users

---

packages/apollos-data-connector-analytics/package.json
yarn.lock

Upgrades `analytics-node` to fix a security vulnerability in `axios`.
**Manual QA**

Upgrades Analytics Package

---

packages/apollos-church-api/src/server.js
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/src/auth/token.js
packages/apollos-server-core/package.json
yarn.lock

I was running into issues on Willow due to multiple versions of the `Apollo Server` package. This should fix those issues, by ensuring that none of the sub packages are using their own version of `Apollo Server`
Also snuck in a fix for the formatError` function in production.
n/a
n/a
n/a
**Manual QA**

Stabilize apollo server versions

---

CACHING.md

Adds a document describing our current caching strategy. 
n/a
Read the documentation in `CACHING.md`
I tried to make my mom proofread this, but she wasn't interested. 
**Manual QA**

Caching documentation

---

packages/apolloschurchapp/index.js

@vinnyjth explain to me why I had to do this to get this to work but it seems to work as is for everyone else? Shouldn't it `.default`?
**Manual QA**

Use default import in root index

---

packages/apollos-data-connector-rock/src/auth/data-source.js

Adds the "persisted=true" attribute when logging in users via the API. According to Jon E, this should help reduce cookies expiring early. We have noticed that it adds an expiresAt time to the cookies returned when logging in. 
Newspring has been testing this for a while now with no bad side effects. They have noticed that auth errors related to invalid cookies have been going down, since launching this new code. 
n/a
1. Open the app.
2. Login
3. Click around (which confirms your session is indeed valid)
n/a
**Manual QA**

Adds persisted cookies

---

packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js

Remove unneeded `ThemeMixin` that was breaking stuff in `WeekendContentItem`
**Manual QA**

Fixes custom theme color references on weekends

---

packages/apollos-ui-mapview/src/MapView/MapView.stories.js
packages/apollos-ui-mapview/src/MapView/MapView.tests.js
packages/apollos-ui-mapview/src/MapView/__snapshots__/MapView.tests.js.snap
packages/apollos-ui-mapview/src/MapView/index.js

This PR adds a `buttonTitle` prop to allow the "confirmation message" to be configurable. 
N/A
Check the `MapView` > `buttonTitle` story
New snapshot to cover the new prop"
**Manual QA**

Allows Mapview button text to be configurable

---

packages/apollos-ui-mapview/jest.setup.js

I noticed when running tests there was a warning related to animations running in `ui-mapview`. A google search led me to [this](https://github.com/facebook/react-native/issues/11094) and a solution found [here](https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/642#issuecomment-345672238).
All this does is mock `NativeAnimatedHelper` in `ui-mapview`. I ran through other places we were using `Animated` but we either don't have test coverage over these places or they weren't throwing this warning.
N/A
Run `yarn test` and you shouldn't see this anymore in the console.
> Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove …

Cleaned up animation tests

---

packages/apollos-ui-mapview/jest.setup.js
packages/apolloschurchapp/jest.setup.js

Fixes another animated test warning

---

packages/apolloschurchapp/ios/Podfile.lock
packages/apolloschurchapp/package.json
yarn.lock

Videos are crashing on iOS on real devices. On the sim the error can be dismissed.
**Manual QA**

Fixes Videos on iOS

---

packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.js
packages/apolloschurchapp/src/testing-control-panel/index.js

Checks for a non-http type URL and uses the RN Linking library instead of the in-app browser.
**NOTE:** if they don't have an email client on their phone the link will appear to do nothing (an error shows on debug).
None.
Boot the app on a real device, the sim doesn't have Mail installed.
None.
**Manual QA**

Adds mailto link support

---

packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.tests.js
packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap

PR got merged with inconsistent tests, so we'll need to merge this PR so we can merge PR's again :) 
**Manual QA**

Removes images from the mocks to fix inconsistent tests

---

packages/apolloschurchapp/ios/apolloschurchapp/Info.plist

Enables background audio playback in iOS
None.
Play a video and watch it keep going in the background. Works on a sim.
None.
**Manual QA**

Adds background audio playback

---

packages/apollos-ui-connected/package.json
packages/apollos-ui-kit/src/theme/__snapshots__/withTheme.tests.js.snap
packages/apollos-ui-kit/src/theme/withTheme.js
packages/apollos-ui-kit/src/theme/withTheme.tests.js

With theme works with overrides

---

packages/apolloschurchapp/ios/Podfile.lock
packages/apolloschurchapp/package.json
packages/apolloschurchapp/src/user-web-browser/__tests__/__snapshots__/BrowserWithUserCookie.tests.js.snap
yarn.lock

This PR updates `react-native-webview` to version 7 to comply with Apple's deprecation of the UIWebView.
N/A
Run `yarn` and make sure that the "Open Web Browser With User Cookie" option in the Testing Control Panel works correctly.
N/A
**Manual QA**

Update for UIWebView Deprecation

---

packages/apollos-ui-kit/README.md

Added a readme to uikit

---

package.json
scripts/watch.js
yarn.lock

[Companion PR](https://github.com/ApollosProject/apollos-templates/pull/1)
We'll merge the PR here in Apollos-apps first, and then immediately merge the PR in `apollos-templates`
The goal of this PR is to replace `yarn link` with a better alternative. The reason yarn link is an issue is because we include the `graphql`  dependency in our data-connector packages for testing purposes. When those are included in the node_modules tree for an app along with the `graphql`  package you  `includine` for the server, the graphql package throws errors when doing things like checking values in the schema (which we do with `Node.get()`) because it doesn't like the fact multiple GraphQL packages are found. Normally this wouldn't be an issue because yarn dedupes the tree **BUT** remember that we are …

Switch from `yarn link` to `yalc` for API packages. 

---

packages/apollos-data-connector-algolia-search/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json
packages/apollos-data-schema/src/index.js
packages/apollos-server-core/package.json
packages/apollos-server-core/src/index.js
yarn.lock

Besides the addition of the `cacheControl` directive in two places, this PR is very straightforward. 
The `cacheControl` is needed in two places, both places where we rely on a schema that is stitched together by us, rather than `ApolloServer`. The `ApolloServer` injects certain schema elements, such as the `cacheControl` directive and the `Upload` scalar, that we don't get when creating the schema by hand. 
Previously, missing the `cacheControl` scalar was a non-issue, but now those schemas generated outside the context of `ApolloServer` were throwing an error in GraphQL 14 / Apollo Server 2.11. Adding the `cacheControl` directive anywhere we create a schema by hand has fixed those issues.
Companion PR: https://github.com/ApollosProject/apollos-templates/pull/6
1. Run tests ;) 
2. Clone …

Updates apollo-server-core so that we can use graphql 14.0.0 

---

packages/apollos-ui-connected/src/RockAuthedWebView/RockAuthedWebView.tests.js
packages/apollos-ui-connected/src/RockAuthedWebView/index.js
packages/apollos-ui-connected/src/index.js

Forgot to export these last time 😬
**Manual QA**

Exports RockAuthedWebView

---

packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/content-items/data-source.js
packages/apollos-data-connector-rock/src/content-items/resolver.js
packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
packages/apollos-data-connector-rock/src/features/__tests__/index.js
packages/apollos-data-connector-rock/src/features/data-source.js
packages/apollos-data-connector-rock/src/features/resolver.js
packages/apollos-data-schema/src/index.js

This adds the `HorizontalCardListFeature`. It's basically a duplicate of the `VerticalCardListFeature` so no real surprises here. This PR also moves the hyphenation functionality we had in the `ContentItem` resolver to the data source so it can be used more broadly. 
🤷‍♂ 
Run test. Inspect outputs and snapshots. 
This should have better coverage than before this PR was created.
**Manual QA**

Add horizontal card list feature

---

packages/apollos-data-schema/src/index.js

I should have removed this field from the cache originally, seeing as it's specific to a user. 
n/a
No great way to test this :)
n/a
**Manual QA**

Remove upNext and percentComplete from cache.

---

packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
packages/apollos-data-connector-rock/src/features/data-source.js
packages/apollos-data-connector-rock/src/features/resolver.js
packages/apollos-data-schema/src/index.js

Related client PR: https://github.com/ApollosProject/apollos-templates/pull/27
**Manual QA**

Updates CardListItem Features Resolver

---

packages/apollos-ui-auth/src/Password/EmailEntryConnected.js
packages/apollos-ui-auth/src/SMS/PhoneEntryConnected.js
packages/apollos-ui-auth/src/SMS/VerificationConnected.js
packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js

Fixes the following error that pops up in certain client apps: 
**Manual QA**

Remove object syntax from JSX

---

packages/apollos-ui-fragments/src/features.js

Companion PR: https://github.com/ApollosProject/apollos-templates/pull/30
Moves the Features data into the `fragments` package, so that we can safely migrate the Features into the `ui-connected` package. 
You should be able to render the home feed in `templates` without anything changing. 
**Manual QA**

Feature fragments

---

packages/apollos-ui-connected/src/VerticalCardListFeature/VerticalCardListFeature.stories.js
packages/apollos-ui-connected/src/VerticalCardListFeature/VerticalCardListFeature.tests.js
packages/apollos-ui-connected/src/VerticalCardListFeature/__snapshots__/VerticalCardListFeature.tests.js.snap
packages/apollos-ui-connected/src/VerticalCardListFeature/index.js
packages/apollos-ui-connected/src/index.js

Companion PR to https://github.com/ApollosProject/apollos-templates/pull/34. Merge this PR first.
This just packages the `VerticalCardListFeature` into `ui-connected`.
open the app. check the stories. run the tests.
Actually, tests on this PR wont run because of some mocking error in ui-connected that needs to be resolved. This PR is unmergable until it's resolved.
👍 
**Manual QA**

Moves VerticalCardListFeature component to ui-connected packages

---

packages/apollos-ui-connected/src/ActionListFeature/ActionListFeature.stories.js
packages/apollos-ui-connected/src/ActionListFeature/ActionListFeature.tests.js
packages/apollos-ui-connected/src/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
packages/apollos-ui-connected/src/ActionListFeature/index.js
packages/apollos-ui-connected/src/index.js

Companion PR to https://github.com/ApollosProject/apollos-templates/pull/32. Merge this PR first.
This just packages the `ActionListFeature` that is usually used the home tab.
This component accepts a `loadingStateObject` which isn't really an object but an array of objects. However, this is our standard prop naming convention for this type of prop. I am also not entirely sure it changes much of how the loading state renders. Nonetheless, at some point I needed it.
open the app. check the stories. run the tests.
Actually, tests on this PR wont run because of some mocking error in ui-connected that needs to be resolved. This PR is unmergable until it's resolved.
👍 
**Manual QA**

Moves ActionListFeature to ui-connected

---

packages/apollos-ui-connected/src/HorizontalCardListFeature/HorizontalCardListFeature.stories.js
packages/apollos-ui-connected/src/HorizontalCardListFeature/HorizontalCardListFeature.tests.js
packages/apollos-ui-connected/src/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
packages/apollos-ui-connected/src/HorizontalCardListFeature/index.js
packages/apollos-ui-connected/src/index.js
packages/apollos-ui-fragments/src/features.js

Companion PR to https://github.com/ApollosProject/apollos-templates/pull/33. Merge this PR first.
This just packages the `HorizontalCardListFeature` with `ui-connected`.
open the app. check the stories. run the tests.
Actually, tests on this PR wont run because of some mocking error in ui-connected that needs to be resolved. This PR is unmergable until it's resolved.
👍 
**Manual QA**

Move horizontal card list feature to core

---

packages/apollos-ui-connected/src/CampaignItemListFeature/CampaignItemListFeature.stories.js
packages/apollos-ui-connected/src/CampaignItemListFeature/CampaignItemListFeature.tests.js
packages/apollos-ui-connected/src/CampaignItemListFeature/__snapshots__/CampaignItemListFeature.tests.js.snap
packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
packages/apollos-ui-connected/src/index.js

Companion PR to https://github.com/ApollosProject/apollos-templates/pull/31. Merge this PR first.
This just packages the `CampaignListItemFeature` that is usually used at the top of the home tab.
open the app. check the stories. run the tests.
Actually, tests on this PR wont run because of some mocking error in ui-connected that needs to be resolved. This PR is unmergable until it's resolved.
👍 
**Manual QA**

Adds CampaignItemListFeature to ui-connected package

---

packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeed.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/getFeedFeatures.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/index.js
packages/apollos-ui-connected/src/index.js

This is the companion PR to https://github.com/ApollosProject/apollos-templates/pull/38. Merge this PR first.
This PR moves the "features feed" usually seen on the home tab to the `ui-connected` package.
It's really just a migration and mild refactor to follow establish patterns. It is very much so hard coded to the home tab "features" and needs additional work int he future to be flexible. Moving it now, however, lets us make changes more easily.
launch the app and tap around
This component didn't have tests before. I'm going to try to get some tests and possibly some stories done before this is merged.
**Manual QA**

Adds FeaturesFeedConnected component

---

packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
packages/apollos-data-connector-rock/src/features/__tests__/index.js
packages/apollos-data-connector-rock/src/features/data-source.js

Adds an algorithm that mimics the user feed. 
Pull this PR (https://github.com/ApollosProject/apollos-templates/pull/37) in templates and run the app. You'll see a (non-paginated) home feed. 
Tests covering new functionality. 
**Manual QA**

Adds User feed algorithm

---

packages/apollos-data-connector-rock/src/auth/token.js

Temp fix until we can figure out how to gracefully attempt a re-auth.
**Manual QA**

Extends Auth Token Expiration

---

packages/apollos-ui-analytics/package.json
packages/apollos-ui-auth/package.json
packages/apollos-ui-connected/package.json
packages/apollos-ui-htmlview/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
packages/apollos-ui-kit/src/theme/defaultTheme.js
packages/apollos-ui-kit/src/theme/types/dark.js
packages/apollos-ui-mapview/package.json
packages/apollos-ui-media-player/package.json
packages/apollos-ui-notifications/package.json
packages/apollos-ui-onboarding/package.json
packages/apollos-ui-passes/package.json
packages/apollos-ui-scripture/package.json

Fixes bug where status bar icons blend into status bar background.
By default theme type is light so the background of the status bar will be white. We need the barStyle to be 'dark-content' to put a dark color on the time, wifi icon and battery icon. When we set dark as the theme type in the app theme.js that changes the background color of the status bar to a dark color. So, in that case we want the time, wifi icon and battery icon to be white or light color so the dark.js should default 'barStyle' to 'light-content'.
Android should look like this for dark and light theme.
Fire up Android and test the dark and light theme.
**Manual QA**

Fix barStyle to be correct for light and dark theme types

---

packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.js
packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.js
packages/apollos-ui-kit/src/ActionListCard/ActionListCard.stories.js
packages/apollos-ui-kit/src/ActionListCard/ActionListItem/ActionListImage.js
packages/apollos-ui-kit/src/ActionListCard/ActionListItem/ActionListImage.tests.js
packages/apollos-ui-kit/src/ActionListCard/ActionListItem/__snapshots__/ActionListImage.tests.js.snap
packages/apollos-ui-kit/src/ActionListCard/ActionListItem/index.js

Adds the Calendar action list images to the ActionListItem, if the item has no image and the related node has a `start`. 
I know that this isn't the best solution to this problem, we ultimately will need something more composable where the magic is exposed in another layer. However, in order to move forward with updating Willow, I propose we start here. It will be easy enough to move the logic that's happening the bottom layer and move it somewhere else in the tree.
I put together a story called "ActionList/event actions"
Snapshot tests over new component
**Manual QA**

Adds CalendarActionImages from Willow and for Willow

---

packages/apollos-ui-connected/src/ContentCardConnected/ContentCardComponentMapper/contentCardComponentMapper.js
packages/apollos-ui-connected/src/ContentCardConnected/index.js
packages/apollos-ui-connected/src/index.js

Adds backwards compatibility for contentCardComponentMapper 

---

packages/apollos-ui-mapview/src/MapView/index.js

n/a
2. Visit the location finder screen
3. All should look the same
n/a
**Manual QA**

Add withTheme to mapview confirm button so it can be overriden

---

packages/apollos-ui-mapview/src/MapView/MapView.tests.js
packages/apollos-ui-mapview/src/MapView/__snapshots__/MapView.tests.js.snap
packages/apollos-ui-mapview/src/MapView/index.js

Allows me to go back to using the Core MapView. Essentially just makes sure that campuses with a null lat/long aren't being rendered on the MapView. They are still visible in the sliding list at the bottom. 
Before this PR, those campuses would show errors. 
**Manual QA**

Ensures the mapview renders fine with campuses with a null lat/long

---

local.graphql
packages/apollos-data-schema/src/index.js
packages/apollos-ui-fragments/src/features.js

I'm have trouble generating the correct `local.graphql` file so I manually fixed it, @vinnyjth can you point me to what I should be doing? Looks like we have a script that runs when we `yarn start` that looks for changes, but couldn't figure it out.
Also, I believe I need a canary build for `apollos-data-schema` and `apollos-ui-fragments` to get the Porch App to work with the new `WebviewFeature` so I alphabetized the schema and fragment.
**Manual QA**

Schema fix and trigger canary build

---

package.json
packages/apollos-eslint-config/client.js
packages/apollos-eslint-config/package.json
packages/apollos-ui-analytics/package.json
packages/apollos-ui-auth/package.json
packages/apollos-ui-kit/package.json
packages/apollos-ui-media-player/package.json
packages/apollos-ui-notifications/package.json
packages/apollos-ui-onboarding/package.json
packages/apollos-ui-passes/package.json
packages/apollos-ui-prayer/package.json
packages/apollos-ui-scripture/package.json
yarn.lock

All this does is add React's recommended eslint rules for hooks. You know... so you know when you're doing something wrong 😉 
- `yarn`
- open your editor
- go break [a rule](https://reactjs.org/docs/hooks-rules.html)
**Manual QA**

Add eslint plugin for react hooks

---

packages/apollos-ui-connected/src/CampaignItemListFeature/index.js

Fixes "Live" label on Campaign (featured) Items

---

packages/apollos-data-connector-algolia-search/__mocks__/@apollosproject/config.js
packages/apollos-data-connector-algolia-search/src/__tests__/data-source.tests.js
packages/apollos-data-connector-algolia-search/src/data-source.js
packages/apollos-data-connector-algolia-search/src/jobs.js

We were updating settings on algolia with every request made to the app, this reduces the number of calls to "once per app booting" while maintaining the same sets of functionality. 
n/a
Boot the app, you shouldn't see any errors.
Existing tests continued to work. 
**Manual QA**

Reduces Algolia calls

---

packages/apollos-data-schema/src/index.js
packages/apollos-ui-connected/src/ActionListFeatureConnected/getActionListFeature.js
packages/apollos-ui-connected/src/HeroListFeatureConnected/getHeroListFeature.js
packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/getHorizontalCardListFeature.js
packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/getVerticalCardListFeature.js
packages/apollos-ui-fragments/src/features.js

This PR sets up the context for being able to link feature cards / action list items to URLs or Navigation actions. I also setup a fragment for the `relatedNodes` on all the feed features, so that they can be more easily extended. Right now it's very difficult to make a straightforward change to the `relatedNodes` 
This will help eliminate custom code in Grace, Willow, and the The Porch (and probably NS and CF as well)
n/a
2. Make sure the feature feed loads. (I will follow up with a template PR demonstrating a link)
n/a
**Manual QA**

Adds core support for URL type and opening URLs Actions in w/ Features

---

packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
packages/apollos-data-connector-rock/src/features/__tests__/index.js
packages/apollos-data-connector-rock/src/features/data-source.js
packages/apollos-data-schema/src/index.js
packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/ActionListFeature.tests.js
packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.tests.js
packages/apollos-ui-connected/src/ActionListFeatureConnected/__snapshots__/ActionListFeatureConnected.tests.js.snap
packages/apollos-ui-fragments/src/features.js

Adds action list primary action support (a nice wide button)

---

packages/apollos-ui-kit/__mocks__/react-native-safe-area-context.js
packages/apollos-ui-kit/babel.config.js
packages/apollos-ui-kit/src/ActionList/ActionList.stories.js
packages/apollos-ui-kit/src/ActionList/ActionList.tests.js
packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListImage.js
packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListItem.stories.js
packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListItem.tests.js
packages/apollos-ui-kit/src/ActionList/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
packages/apollos-ui-kit/src/ActionList/ActionListItem/index.js
packages/apollos-ui-kit/src/ActionList/__snapshots__/ActionList.tests.js.snap
packages/apollos-ui-kit/src/ActionList/index.js

Adds action list event icons, ported from ActionListCard event icons

---

packages/apollos-ui-kit/src/TouchableScale/index.js

Fix issue when changing "onPress" prop on TouchableScale

---

packages/apollos-data-connector-rock/src/followings/data-source.js

This not being a request class was causing problems on one of our downstream functions. This standardizes the return type.
**Manual QA**

Type safes followings return type

---

packages/apollos-ui-analytics/package.json

Make metarouter analytics a peerDependency

---

packages/apollos-ui-kit/src/Avatar/AvatarCloud/index.js

fix null avatar image case

---

.github/workflows/linting.yml
.github/workflows/unittest.yml

Adds Jest and ESLint to Github Actions.
None.
Wait for the green check, should confirm Codecov is still working.
duh
**Manual QA**

Adds Github Actions CI

---

packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeature/index.js
packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeatureConnected.tests.js
packages/apollos-ui-connected/src/HeroListFeatureConnected/__snapshots__/HeroListFeatureConnected.tests.js.snap
packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/index.js
packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.js
packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.tests.js
packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/__snapshots__/HorizontalCardListFeatureConnected.tests.js.snap
packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/index.js
packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.tests.js
packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/__snapshots__/VerticalCardListFeatureConnected.tests.js.snap

This PR ensures that features that don't have any content won't show up. You will no longer see orphaned headers or sub-headers. 
After features are done loading, if we don't have any content, we render null. 
n/a
Hard to test with core rock broken 😅 
Extensive tests over frontend using mocks + utilizing existing coverage.
**Manual QA**

Features should not render if they have no content

---

.github/workflows/titles.yml
.mergify.yml

chore: Adds Conventional Commits rules to merge

---

.github/workflows/publish.yml

This isn't working, I didn't authenticate properly the first time
**Manual QA**

chore: Publishes Canary Packages

---

.github/workflows/linting.yml
.github/workflows/publish.yml
.github/workflows/titles.yml
.github/workflows/unittest.yml

Explicitly defines the Node version and gets rid of the matrix (we don't use it)
**Manual QA**

chore: Simplifies CI Node versions

---

.github/workflows/linting.yml
.github/workflows/publish.yml
.github/workflows/titles.yml
.github/workflows/unittest.yml

chore: Fetches all tags in Canary publish

---

codecov.yml

chore: Cleaned up Codecov

---

.github/workflows/publish.yml

I seriously don't even know anymore
**Manual QA**

chore: Updates NPM Action

---

packages/apollos-data-schema/src/index.js

Very simple. Adds a new `ENUM` value to the schema that we can tie to a new route in the Templates Repo. No way to test, and really nothing to test, besides that the app boots. 
**Manual QA**

feat: Adds open_node action to schema

---

packages/apollos-data-connector-church-online/src/__tests__/__snapshots__/resolver.tests.js.snap
packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js
packages/apollos-data-connector-church-online/src/data-source.js

feat: Upgrades Church Online to GraphQL Endpoint

---

packages/apollos-ui-connected/src/ContentCardConnected/ContentCardConnected.stories.js
packages/apollos-ui-connected/src/testUtils/index.js

This PR is pretty simple, it shows off how ContentCardConnected can now render non-Content types. I've added the ability for events to be `cards` (in the client storybook mocks only) and then rendered an Event as a default card. Pretty neat. 
n/a
Look for the `example event` story. 
n/a
**Manual QA**

feat: ContentCardConnected stories. 

---

packages/apollos-ui-connected/src/index.js

Forgot an export....
**Manual QA**

fix: Added missing node-single export

---

packages/apollos-ui-notifications/package.json
yarn.lock

chore: Updates Onesignal Dependency

---

ApollosStorybook/ios/Podfile
ApollosStorybook/ios/Podfile.lock

Not having this was causing an obnoxious error to pop up on app boot. You could dismiss it, but you had to do it every time teh app fully refreshed. 
You'll need to clean your build folder before you build in order to get rid of the error. 
**Manual QA**

fix: Included a permissions lib

---

.github/workflows/release-beta.yml
.github/workflows/release-canary.yml

This will first publish to GPR (pretty much for show) and then publish the real thing to NPM and push up tags and stuff.
**Manual QA**

chore: Adds Beta Release Workflow

---

packages/apollos-ui-prayer/__mocks__/@react-native-community/async-storage.js
packages/apollos-ui-prayer/src/PrayerInput/index.js

This will autosave prayer text after 3 sec in async storage
**Manual QA**

feat: Autosave Prayer Text

---

packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.js

Android doesn't have the concept of a notifications prompt ([OneSignal SDK](https://documentation.onesignal.com/docs/sdk-reference#ospermissionsubscriptionstate)) so this just bypasses that for Android.
**Manual QA**

fix: Fixes Android Notifications Onboarding

---

packages/apollos-data-connector-rock/src/campuses/__tests__/__snapshots__/resolver.tests.js.snap
packages/apollos-data-connector-rock/src/campuses/data-source.js
packages/apollos-data-connector-rock/src/campuses/resolver.js

Best way to test is with the linked setup and either the API or campus select screen.  
**Manual QA**

fix: Move campus fields resolution to resolver

---

package.json

It didn't do an official github release when I thought it would. Next time I'm going to try without `conventional-graduate` and see what happens.
**Manual QA**

chore: Adds TODO to Release Process

---

packages/apollos-data-schema/src/index.js

Replaces `features` with `featureFeed`

feat: Adds FeatureFeed Schema

---

packages/apollos-data-connector-rock/src/feature-feeds/__tests__/FeatureFeed.tests.js
packages/apollos-data-connector-rock/src/feature-feeds/__tests__/__snapshots__/FeatureFeed.tests.js.snap
packages/apollos-data-connector-rock/src/feature-feeds/index.js

chore: Adds Feature Feed Tests

---

packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.js

This causes a strange bug when `refetching` where loading is never `false`. You'll see it if you open the new feature driven discover feed and try to pull to refetch. 
**Manual QA**

chore: Missing fetch policy

---

packages/apollos-ui-connected/src/SearchFeedConnected/NoResults.js
packages/apollos-ui-connected/src/SearchFeedConnected/SearchFeedConnected.tests.js
packages/apollos-ui-connected/src/SearchFeedConnected/SearchInputHeader/SearchInputHeader.tests.js
packages/apollos-ui-connected/src/SearchFeedConnected/SearchInputHeader/__snapshots__/SearchInputHeader.tests.js.snap
packages/apollos-ui-connected/src/SearchFeedConnected/SearchInputHeader/index.js
packages/apollos-ui-connected/src/SearchFeedConnected/__snapshots__/SearchFeedConnected.tests.js.snap
packages/apollos-ui-connected/src/SearchFeedConnected/getSearchResults.js
packages/apollos-ui-connected/src/SearchFeedConnected/index.js
packages/apollos-ui-connected/src/index.js
packages/apollos-ui-fragments/src/index.js
packages/apollos-ui-fragments/src/searchResults.js

feat: SearchFeed connected components

---

packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.tests.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/__snapshots__/FeaturesFeedConnected.tests.js.snap

chore: Fixes Feature Feed Test

---

packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
packages/apollos-data-connector-rock/src/features/__tests__/index.js
packages/apollos-data-connector-rock/src/features/data-source.js
packages/apollos-data-connector-rock/src/features/resolver.js
packages/apollos-data-schema/src/index.js
packages/apollos-ui-connected/src/ActionBarFeatureConnected/ActionBarFeature/index.js
packages/apollos-ui-connected/src/ActionBarFeatureConnected/ActionBarFeatureConnected.tests.js
packages/apollos-ui-connected/src/ActionBarFeatureConnected/__snapshots__/ActionBarFeatureConnected.tests.js.snap
packages/apollos-ui-connected/src/ActionBarFeatureConnected/getActionBarFeature.js
packages/apollos-ui-connected/src/ActionBarFeatureConnected/index.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/featuresFeedComponentMapper.js
packages/apollos-ui-fragments/src/features.js

```
{
homeFeedFeatures {
features {
id
... on ActionBarFeature {
title
actions {
title
icon
id
relatedNode {
... on Url {
id
url
}
}
}
}
}
} 
}
```
**Manual QA**

feat: ActionBarConnected

---

packages/apollos-ui-analytics/src/CoreNavigationAnalytics.js
packages/apollos-ui-analytics/src/TrackEventWhenLoaded.js
packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/ContentSingleFeaturesConnected.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeature/index.js
packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/index.js
packages/apollos-ui-connected/src/HorizontalFeedConnected.js
packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/index.js
packages/apollos-ui-connected/src/NodeSingleConnected/index.js
packages/apollos-ui-connected/src/SearchFeedConnected/index.js
packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
packages/apollos-ui-connected/src/features/ScriptureFeature.js
packages/apollos-ui-connected/src/features/TextFeature.js
packages/apollos-ui-connected/src/testUtils/index.js
packages/apollos-ui-kit/src/ActionListCard/ActionListItem/index.js
packages/apollos-ui-kit/src/FeaturedCard/index.js
packages/apollos-ui-kit/src/HighlightCard/index.js
packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
packages/apollos-ui-kit/src/inputs/Radio/Radio.js
packages/apollos-ui-mapview/src/MapViewConnected/MapViewConnected.js
packages/apollos-ui-prayer/src/screens/AddPrayerScreenConnected/index.js
packages/apollos-ui-prayer/src/screens/ConfirmationDialogScreen/index.js

Fixed two types of warnings: 
1. Circular imports (only visible from JS console) 
2. All of the propType warnings I could find
3. probably some other stuff 
Still three big warnings to solve that are not in our package. To fix them we need to...
- Update `react-native-safe-area-view` one dot version. (0.14.3 I think?)
- Update `react-apollo` to 3.0
- Update `react-storybook` to 5.3
**Manual QA**

chore: Cleanup warnings in dev mode

---

.github/workflows/titles.yml

this should allow dependabot titles to pass

chore(ci): Updates PR titles

---

packages/apollos-ui-connected/src/index.js

Forgot to export this last time 🤦‍♂️

fix: Exports Correct Feed Features Query

---

packages/apollos-data-connector-rock/src/followings/resolver.js

It's supported in the schema but it wasn't hooked up in the resolvers. I noticed it at one point in Grace, but I managed to track it down while upgrading NS.  
**Manual QA**

fix: Users can follow/like weekend content items

---

packages/apollos-data-connector-rock/src/rock-constants/__tests__/__snapshots__/rock-constants.tests.js.snap
packages/apollos-data-connector-rock/src/rock-constants/__tests__/rock-constants.tests.js
packages/apollos-data-connector-rock/src/rock-constants/index.js

fix: Support Rock 11 out of the box, patch InteractionComponent calls. 

---

packages/apollos-ui-prayer/src/PrayerCard/index.js
packages/apollos-ui-prayer/src/PrayerInput/index.js
packages/apollos-ui-prayer/src/screens/AddPrayerScreenConnected/index.js

fix: Clear prayer text on send

---

packages/apollos-server-core/src/universalLinking/__tests__/universalLinking.tests.js
packages/apollos-server-core/src/universalLinking/index.js

feat: Allow universal linking redirect function to be async

---

packages/apollos-ui-test-utils/src/ApolloStorybookDecorator.js
packages/apollos-ui-test-utils/src/createPossibleType.js
packages/apollos-ui-test-utils/src/index.js
packages/apollos-ui-test-utils/src/typeDefsMock.js

fix: Add storybook decorator back

---

packages/apollos-ui-media-player/package.json

fix: Include storybook stories

---

package.json

I always try to run yarn generate-stories from the root and then realize it does nothing :) this fixes that

chore: Simplifies Story Generation

---

packages/apollos-ui-media-player/src/RNVideo.tsx

fix: Cover image vanishes as soon as media loads

---

package.json
scripts/watch.js

- chore: Simplifies Story Generation
- chore: Extends Watch Script to Include UI Packages

chore: Extends Watch to Include UI Pkgs

---

packages/apollos-ui-connected/src/ScriptureNodeConnected/ScriptureNodeConnected.js
packages/apollos-ui-connected/src/ScriptureNodeConnected/ScriptureNodeConnected.stories.js
packages/apollos-ui-connected/src/ScriptureNodeConnected/ScriptureNodeConnected.tests.js
packages/apollos-ui-connected/src/ScriptureNodeConnected/__snapshots__/ScriptureNodeConnected.tests.js.snap
packages/apollos-ui-connected/src/ScriptureNodeConnected/getScriptureNode.js
packages/apollos-ui-connected/src/ScriptureNodeConnected/index.js
packages/apollos-ui-fragments/src/interfaces.js

feat: Scripture node connected

---

.github/workflows/titles.yml

chore: Fix title action

---

.github/workflows/titles.yml
package.json
packages/apollos-data-connector-rock/src/action-algorithms/index.js
packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
packages/apollos-data-connector-rock/src/content-items/resolver.js
packages/apollos-data-connector-rock/src/prayer-request/__tests__/__snapshots__/data-source.tests.js.snap
packages/apollos-data-connector-rock/src/prayer-request/__tests__/data-source.tests.js
packages/apollos-data-connector-rock/src/prayer-request/data-source.js
packages/apollos-data-schema/src/index.js
packages/apollos-ui-fragments/src/content.js
scripts/watch.js

chore: Catch next upto master

---

packages/apollos-data-connector-rock/src/interactions/data-source.js

Breaking up the request to the interaction custom endpoint because something is breaking (maybe ASP.NET)

fix: Splits Interaction Requests

---

packages/apollos-ui-connected/src/NodeSingleConnected/index.js

feat: Improve node single connected to more closely mimic ContentSingle. 

---

packages/apollos-data-schema/src/index.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js

This will use the Rock token to authenticate URLs clicked through a feature

feat: Allows Action URLs to be Authenticated

---

packages/apollos-ui-mapview/jest.setup.js
packages/apollos-ui-mapview/package.json
packages/apollos-ui-mapview/src/MapViewConnected/MapViewConnected.js
packages/apollos-ui-mapview/src/index.js
packages/apollos-ui-mapview/src/utils/getUserLocation.js
packages/apollos-ui-onboarding/jest.setup.js
packages/apollos-ui-onboarding/package.json
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/requestLocation.android.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/requestLocation.ios.js
yarn.lock

I unified our approach to seeing if a user has granted location permission. 
I also followed the instructions on the `react-native-geolocation-service` repo to use the library correctly. Mainly including always asking for permissions / checking permissions before assuming we can grab location. 
**Manual QA**

fix: Inconsistent results when using the LocationFinder

---

packages/apollos-data-connector-algolia-search/package.json
packages/apollos-data-connector-analytics/package.json
packages/apollos-data-connector-bible/package.json
packages/apollos-data-connector-church-online/package.json
packages/apollos-data-connector-onesignal/package.json
packages/apollos-data-connector-passes/package.json
packages/apollos-data-connector-rock/package.json

chore: Move schema to peer dep

---

ApollosStorybook/yarn.lock
packages/apollos-ui-kit/src/ConnectedImage/index.js
packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
packages/apollos-ui-kit/src/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap

The existing implementation had two subtle bugs that caused `maintainAspectRatio` to not work if no aspect ratio was given. 
The first bug was the image width/height were never being cached. That was fixed by making sure the current attributes were being referenced `onLoad`. 
The second bug was that we were using the `width` and `height` attribute on the array of cached sources, rather than on one of the sources directly. This was corrected by checking for the `width` and `height`. This has subtle changes to how the app looks, but those changes will reflect the intent in code more closely. Might be good to click around in storybook before merging this. 
Images of tweak working in NS.
**Manual QA**
> The purpose of PR Review is to _improve the quality …

fix: Connected image Aspect Ratio

---

packages/apollos-data-connector-rock/src/action-algorithms/index.js

Using a `channelId` argument, this algorithm will return the children of a given series

feat: Adds Series Children Algorithm

---

packages/apollos-ui-auth/src/index.js

fix: Fixes Extra Auth Header

---

packages/apollos-data-connector-rock/src/action-algorithms/index.js
packages/apollos-data-connector-rock/src/features/data-source.js
packages/apollos-data-connector-rock/src/features/resolver.js
packages/apollos-data-schema/src/index.js

This adds a `UsersPrayers` feature option to the config, returning the prayer list of a specific user

feat: Adds User Prayers Feature (API)

---

packages/apollos-ui-connected/src/NodeSingleConnected/index.js

fix: Dark mode not working w/ node single connected

---

packages/apollos-ui-connected/package.json
packages/apollos-ui-connected/src/utils/uploadPhoto/index.js
yarn.lock

fix: Fix image uploading.

---

packages/apollos-ui-connected/src/ContentHTMLViewConnected/ContentHTMLViewConnected.js
packages/apollos-ui-connected/src/ContentNodeConnected/ContentNodeConnected.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
packages/apollos-ui-connected/src/FeaturesFeedConnected/featuresFeedComponentMapper.js
packages/apollos-ui-connected/src/NodeFeaturesConnected/NodeFeaturesConnected.js
packages/apollos-ui-connected/src/NodeSingleConnected/index.js
packages/apollos-ui-connected/src/ScriptureNodeConnected/ScriptureNodeConnected.js
packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
packages/apollos-ui-kit/src/index.js
packages/apollos-ui-kit/src/theme/__snapshots__/withTheme.tests.js.snap
packages/apollos-ui-kit/src/theme/index.js
packages/apollos-ui-kit/src/theme/withTheme.js
packages/apollos-ui-kit/src/theme/withTheme.tests.js

Nothing crazy here. Will need these overrides on Newspring though. 
**Manual QA**

feat: withTheme overrides for various features (and new shorthand for adding withTheme overrides) 

---

packages/apollos-ui-connected/src/ScriptureNodeConnected/index.js
packages/apollos-ui-connected/src/index.js

fix: Missing scripture node export

---

packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js

fix: HTMLVIew shouldn't try and show images with relative urls

---

ApollosStorybook/ios/Podfile.lock
ApollosStorybook/yarn.lock
packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js

fix: Block quotes weren't using theme values

---

packages/apollos-bugsnag/src/index.js

This will help with filtering errors by custom headers, which will allow us to filter server errors by client versions. 
**Manual QA**

feat: Move Bugsnag headers object to it's own tab

---

packages/apollos-data-connector-postgres/src/postgres/index.js

feat: Accept DB options from apollos config

---

packages/apollos-data-schema/src/index.js

Right now it's taking a couple of hours for comments to show up in the app. 
**Manual QA**

fix: Added a max age to the comment field

---

packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.js
packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.stories.js
packages/apollos-ui-prayer/src/PrayerInput/index.js

fix: Prayer and Comment text inputs were invisible in dark mode.

---

packages/apollos-data-connector-postgres/src/comments/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/comments/dataSource.js

feat: Set default comment visibility to public and make private comments private

---

lerna.json

This will allow us to use the ! to specify breaking changes, better than BREAKING CHANGE footers since we squash

chore: Switches the Conventional Commits changelog preset

---

packages/apollos-data-connector-postgres/src/comments/dataSource.js

This is now the second time I've made this mistake 🙃  It's tricky because there's no good way to test for this, it only shows up when using Postgres. 
I dug into options a little bit so that sqlite will reject invalid values in the same manner that Postgres does, but it doesn't look like there are any easy solutions. We might be able to find a way to do this casting in the Sequelize layer. 
**Manual QA**

fix: Missing cast when querying for comments

---

.github/PULL_REQUEST_TEMPLATE.md

chore: Simplifies PR template

---

ApollosStorybook/loadConfig.js
ApollosStorybook/yarn.lock
packages/apollos-data-connector-postgres/src/comments/dataSource.js
packages/apollos-ui-connected/src/NodeSingleConnected/NodeSingleConnected.stories.js
packages/apollos-ui-connected/src/NodeSingleConnected/getMedia.js
packages/apollos-ui-connected/src/NodeSingleConnected/index.js
packages/apollos-ui-fragments/src/interfaces.js

Added in the LiveNode fragment to the NodeSingleConnected component, and then look for the LiveStream property and check if it's live with Media. Active livestreams will now automatically show up on content items that implement LiveNode and are live with media. 
htmlEmbeds are currently not handled. 
There's a new story to test the LiveStream showing up correctly.
**Manual QA**

feat: Add NodeSingleConnected live stream support.

---

package.json

This wasn't happening automatically

fix: insure to generate stories for storybook

---

packages/apollos-data-connector-postgres/src/campus/__tests__/model.js
packages/apollos-data-connector-postgres/src/campus/index.js
packages/apollos-data-connector-postgres/src/campus/model.js
packages/apollos-data-connector-postgres/src/people/__tests__/model.js
packages/apollos-data-connector-postgres/src/people/index.js
packages/apollos-data-connector-postgres/src/people/model.js

Adds a Postgres driven person model.
No real way to test this yet. You could hook it up in `templates` if you wanted, but you would be better off just reading through my tests.

feat: Person and Campus model

---

.github/workflows/ci.yml
.github/workflows/reports.yml

The title check action was failing on push

chore: split out codecov into separate action

---

packages/apollos-ui-connected/src/AddCommentFeatureConnected/__snapshots__/AddCommentFeatureConnected.tests.js.snap
packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.js
packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.stories.js
packages/apollos-ui-kit/src/AddCommentInput/__snapshots__/AddCommentInput.tests.js.snap
packages/apollos-ui-kit/src/FollowList/FollowListSearch/FollowListSearchModal.js
packages/apollos-ui-kit/src/FollowList/FollowListSearch/__snapshots__/FollowListSearch.tests.js.snap
packages/apollos-ui-kit/src/Modal/Modal.stories.js
packages/apollos-ui-kit/src/Modal/Modal.tests.js
packages/apollos-ui-kit/src/Modal/ModalButton.js
packages/apollos-ui-kit/src/Modal/ModalHeader.js
packages/apollos-ui-kit/src/Modal/__snapshots__/Modal.tests.js.snap
packages/apollos-ui-kit/src/Modal/index.js

Adds a confirmation modal for journal entry submission.
Also adds a generic Modal component that doesn't use/require a navigator.
Test the AddCommentInput stories. A modal should pop up upon pressing Submit for the journal entry.
https://user-images.githubusercontent.com/3879073/109359898-3d8a6c80-7854-11eb-9da0-ecd8fc64526d.mov
https://user-images.githubusercontent.com/3879073/109359957-5abf3b00-7854-11eb-8831-06250e95e086.mov

feat: Journal Confirmation Screen

---

.github/workflows/release.yml

This will automatically bump the templates repo and upgrade tool repo after a successful release

chore: automate templates and upgrade tool version bumps

---

ApollosStorybook/ios/Podfile.lock
packages/apollos-ui-connected/src/VerticalPrayerListFeatureConnected/EmptyList.js
packages/apollos-ui-connected/src/VerticalPrayerListFeatureConnected/VerticalPrayerListFeature.js
packages/apollos-ui-connected/src/VerticalPrayerListFeatureConnected/VerticalPrayerListFeature.stories.js
packages/apollos-ui-connected/src/VerticalPrayerListFeatureConnected/VerticalPrayerListFeatureConnected.tests.js
packages/apollos-ui-connected/src/VerticalPrayerListFeatureConnected/__snapshots__/VerticalPrayerListFeatureConnected.tests.js.snap

feat: add empty vertical prayer list state

---

packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js

Not sure when, but we stopped using the custom component prop.

chore: remove feature feed component prop

---

packages/apollos-ui-onboarding/src/Slide/Slide.js
packages/apollos-ui-onboarding/src/Slide/__snapshots__/Slide.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskName.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotifications.tests.js.snap
packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
packages/apollos-ui-onboarding/src/slides/Features/__snapshots__/Features.tests.js.snap
packages/apollos-ui-onboarding/src/slides/Follow/__snapshots__/Follow.tests.js.snap
packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap

fix: Unpressable onboarding buttons

---

packages/apollos-data-connector-postgres/src/people/migrations/002_change_profile_image_url_to_text.js
packages/apollos-data-connector-postgres/src/people/migrations/index.js
packages/apollos-data-connector-postgres/src/people/model.js

I was hitting the limit of `varchar(255)` on Newspring

chore: Add migration to change profileImageUrl type to 'text'

---

packages/apollos-data-connector-postgres/src/comments/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/comments/__tests__/resolver.js
packages/apollos-data-connector-postgres/src/comments/dataSource.js
packages/apollos-data-connector-postgres/src/comments/model.js
packages/apollos-data-connector-postgres/src/user-flags/__tests__/dataSource.js

In the getComment datasource method, we need to float the comments written by users you follow to the top. This PR takes care of that :) 
No easy way to test with the current data in the database. Reading through the tests is your best bet.

feat: Sort users you follow to the top

---

packages/apollos-data-connector-postgres/src/follows/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/follows/dataSource.js

Adds the ability to specify an internal Postgres PK ID in the suggested follows configuration. Needed because sometimes users share an email address, and if that email is configured as a suggestion then all those users end up being matched.
Add a configured suggestion to you templates setup, but use a user that shares an email with another, like so:
```
-
id: a0ff5fd2-31a8-426b-9360-87470087316b
email: vince@classyh.at
campusId: 45893d11-cd72-4a42-b3ee-08814a937e1a
```

feat: Allow specifying suggested follows via Postgres Id

---

packages/apollos-data-connector-postgres/src/follows/dataSource.js
packages/apollos-data-connector-postgres/src/people/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/people/dataSource.js
packages/apollos-data-connector-postgres/src/people/resolver.js
packages/apollos-data-schema/src/index.js
packages/apollos-ui-connected/src/ConnectScreenConnected/ConnectScreenConnected.tests.js
packages/apollos-ui-connected/src/ConnectScreenConnected/__snapshots__/ConnectScreenConnected.tests.js.snap
packages/apollos-ui-connected/src/ConnectScreenConnected/index.js
packages/apollos-ui-connected/src/FollowListSearchModalConnected/getSearchPeople.js
packages/apollos-ui-connected/src/FollowListSearchModalConnected/index.js
packages/apollos-ui-connected/src/index.js
packages/apollos-ui-kit/src/FollowList/FollowListSearch/FollowListSearch.tests.js
packages/apollos-ui-kit/src/FollowList/FollowListSearch/FollowListSearchModal.js
packages/apollos-ui-kit/src/FollowList/FollowListSearch/__snapshots__/FollowListSearch.tests.js.snap
packages/apollos-ui-kit/src/FollowList/FollowListSearch/index.js
packages/apollos-ui-kit/src/FollowList/index.js
packages/apollos-ui-kit/src/index.js

People search! Using the basis of Jimmy and Luke's excellent work. 
A few notes about this PR: 
- Pagination is un-implemented on the front end. I think that's the right choice for now. 
- Still some UI cleanup to be done on the search modal. We can tackle that in another PR. 
Visit the connect tab while linked and hit that shiny "Find People to People" button. Probs should fix my typo 🙃

feat: People Search

---

packages/apollos-data-connector-postgres/src/follows/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/follows/dataSource.js

fix: Don't send push notifications to auto accepted follows

---

packages/apollos-ui-connected/src/ActionBarFeatureConnected/ActionBarFeature/index.js

not sure how this one passed the CI 😂

chore: fix action bar prop type

---

packages/apollos-data-connector-postgres/src/people/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/people/dataSource.js

fix: Don't search non-apollosUsers and trim whitespace

---

.github/workflows/release.yml

chore: Login when releasing canary

---

packages/apollos-ui-connected/src/ConnectScreenConnected/__snapshots__/ConnectScreenConnected.tests.js.snap
packages/apollos-ui-kit/src/FollowList/FollowListSearch/FollowListSearchModal.js
packages/apollos-ui-kit/src/FollowList/FollowListSearch/__snapshots__/FollowListSearch.tests.js.snap
packages/apollos-ui-kit/src/FollowList/FollowListSearch/index.js
packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
packages/apollos-ui-kit/src/inputs/Search/index.js

fix: Add a background to the follow list search

---

packages/apollos-ui-kit/src/AddCommentInput/Editor.js

(my sim was acting up those first few/last taps)

feat: Press on avatar to open comment input

---

packages/apollos-data-connector-rock/src/action-algorithms/index.js
packages/apollos-ui-analytics/src/Provider.js
packages/apollos-ui-analytics/src/index.js
packages/apollos-ui-connected/jest.setup.js
packages/apollos-ui-connected/src/AddCommentFeatureConnected/AddCommentFeatureConnected.js
packages/apollos-ui-connected/src/CommentListFeatureConnected/CommentListFeatureConnected.js
packages/apollos-ui-connected/src/FollowListConnected/FollowListConnected.js
packages/apollos-ui-connected/src/NodeSingleConnected/getTitle.js
packages/apollos-ui-connected/src/NodeSingleConnected/index.js
packages/apollos-ui-connected/src/index.js

On tempaltes, change your `AnalyticsProvider` to
```
<AnalyticsProvider trackFunctions={[console.warn]}>
```
Then like, flag, follow, etc.

feat: Added analytics for new features - journal and following

---

packages/apollos-data-connector-postgres/src/comments/__tests__/__snapshots__/dataSource.js.snap
packages/apollos-data-connector-postgres/src/comments/__tests__/dataSource.js
packages/apollos-data-connector-postgres/src/comments/dataSource.js
packages/apollos-data-connector-postgres/src/comments/resolver.js
packages/apollos-data-schema/src/index.js

Adds mutations to update and delete comments.
Run the following commands. (Make sure to update the CommentId to match what is returned from addComment.)
```
mutation addComment {
addComment(parentId:"WeekendContentItem:f8460101368b38c5aa9bbea8b2b8a625", 
text:"Look at me, a comment!", visibility:PUBLIC){
id
} 
}
mutation updateComment {
updateComment(
commentId:"Comment:e75c37a6-a612-4e1e-8b2e-2c196f725bdc", 
text:"Look at me, an updated comment!", 
visibility:PRIVATE){
id
text
visibility
} 
}
mutation deleteComment {
deleteComment(commentId:"Comment:e75c37a6-a612-4e1e-8b2e-2c196f725bdc") 
}
```

feat: Comment update and delete

---

packages/apollos-ui-connected/src/CommentListFeatureConnected/CommentListFeatureConnected.js

Just what it says in the title. 
Like a comment, then unlike it. Notice the speed. Enjoy instant feedback.

feat: Implement optimistic responses when liking and unliking comments

---

packages/apollos-data-connector-bible/src/__tests__/__snapshots__/resolver.tests.js.snap
packages/apollos-data-connector-bible/src/__tests__/resolver.tests.js
packages/apollos-data-connector-bible/src/data-source.js
packages/apollos-data-connector-bible/src/resolver.js
packages/apollos-data-schema/src/index.js

feat: add books of the bible to scripture references

---

packages/apollos-data-connector-onesignal/src/__tests__/__snapshots__/dataSource.tests.js.snap
packages/apollos-data-connector-onesignal/src/__tests__/dataSource.tests.js
packages/apollos-data-connector-onesignal/src/data-source.js

fix: Onesignal Api change, make sure external_user_ids are strings

---

.github/workflows/release-canary.yml
.github/workflows/release-next.yml
.github/workflows/release.yml
.github/workflows/reports.yml

chore: Setup master workflows for node 12

---

packages/apollos-data-schema/src/index.js
packages/apollos-rock-apollo-data-source/src/index.js
packages/apollos-rock-apollo-data-source/src/request-builder.js

feat: allow sorting of paginated content

---

packages/apollos-ui-auth/src/Entry.stories.js
packages/apollos-ui-auth/src/Password/EmailEntryConnected.js
packages/apollos-ui-auth/src/Password/PasswordEntryConnected.js
packages/apollos-ui-auth/src/Profile/ProfileEntry.js
packages/apollos-ui-auth/src/Profile/ProfileEntryConnected.js
packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntry.js
packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntryConnected.js
packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntryConnected.tests.js
packages/apollos-ui-auth/src/SMS/PhoneEntryConnected.js
packages/apollos-ui-auth/src/SMS/VerificationConnected.js
packages/apollos-ui-auth/src/index.js
packages/apollos-ui-connected/src/LikedContentFeedConnected/LikedContentFeedConnected.js
packages/apollos-ui-prayer/src/screens/AddPrayerScreenConnected/index.js
packages/apollos-ui-prayer/src/screens/PrayerScreen/index.js

This fixes a few issues but mainly cleans up a lot of dead code from the old version of react navigation

fix: fix custom auth text

---

packages/apollos-data-connector-church-online/src/data-source.js

This will load in the next service time, useful for countdowns

chore: get next service from ChOP

---

packages/apollos-data-connector-church-online/src/data-source.js

prevents error before the URL is defined

chore: add livestream safety check

---

packages/apollos-data-connector-rock/src/content-channels/data-source.js

This renames the variable to something more accurate and cleans up the function, removing an unnecessary request

chore: clean up content channels query

---

packages/apollos-rock-apollo-data-source/src/index.js

this allows us to remove one more config variable

chore: define default Rock API address

---

packages/apollos-data-connector-bible/src/__tests__/resolver.tests.js
packages/apollos-data-connector-bible/src/data-source.js

Allows us to drop the need for listing the bible IDs in the config

feat: dynamically find bible ID

---

packages/apollos-data-schema/src/index.js

Apollo Server fixed the reason we couldn't do this at first

chore: change max age to private scope headers

---

packages/apollos-data-connector-bible/src/__tests__/__snapshots__/resolver.tests.js.snap
packages/apollos-data-connector-bible/src/data-source.js

fix: search by abbreviation no longer returns 404

---

packages/apollos-data-connector-postgres/src/postgres/index.js

Heroku SSL certs are self signed.

fix: Don't check postgres server certs

---

packages/apollos-data-connector-bible/src/__tests__/__snapshots__/resolver.tests.js.snap
packages/apollos-data-connector-bible/src/data-source.js

the first time was just lazy...

fix: fix bible request URLs

---

ApollosStorybook/ios/Podfile
ApollosStorybook/ios/Podfile.lock
ApollosStorybook/yarn.lock
package.json
scripts/setup-api.sh
scripts/setup-app.sh

Run this to test the search templates branch: `BRANCH=search-to-apps yarn app`
Everything should happen with that one command.

chore: allows templates branches and app in one command

---

packages/apollos-ui-connected/src/FeaturesFeedTabConnected/FeaturesFeedTabConnected.js
packages/apollos-ui-connected/src/FeaturesFeedTabConnected/index.js
packages/apollos-ui-connected/src/index.js

feat: Add support for feeds using campusIds

---

packages/apollos-ui-connected/src/AddCommentFeatureConnected/addComment.js
packages/apollos-ui-connected/src/CommentListFeatureConnected/getCommentListFeature.js
packages/apollos-ui-fragments/src/features.js

fix: Bug causing new comments to show up only after a refresh

---

packages/apollos-data-connector-rock/src/action-algorithms/index.js
packages/apollos-ui-connected/src/ContentNodeConnected/ContentNodeConnected.js

chore: added custom content header component

---

packages/apollos-ui-kit/src/TableView/Divider.js
packages/apollos-ui-kit/src/TableView/__snapshots__/TableView.tests.js.snap

The little line was going outside the view if it's not full width

chore: modified table view divider style

---

scripts/setup-api.sh
scripts/setup-app.sh

uses the default URL for the API so there's no need to type in the encryption password

chore: makes app developement faster

---

packages/apollos-data-connector-postgres/src/people/dataSource.js
packages/apollos-data-connector-postgres/src/people/resolver.js
packages/apollos-data-schema/src/index.js
packages/apollos-ui-connected/src/FollowListConnected/FollowingListConnected.js
packages/apollos-ui-connected/src/FollowListConnected/FollowingListConnected.tests.js
packages/apollos-ui-connected/src/FollowListConnected/__snapshots__/FollowingListConnected.tests.js.snap
packages/apollos-ui-connected/src/FollowListConnected/getFollowing.js
packages/apollos-ui-connected/src/FollowListConnected/index.js
packages/apollos-ui-connected/src/index.js

- adds getUsersFollowing Query
- Creates ConnectedFollowingList
Available from the testing panel

feat: Following List

---

packages/apollos-ui-onboarding/__mocks__/react-native-safe-area-context.js
packages/apollos-ui-onboarding/src/Onboarding/Onboarding.stories.js
packages/apollos-ui-onboarding/src/Onboarding/Onboarding.tests.js
packages/apollos-ui-onboarding/src/Onboarding/__snapshots__/Onboarding.tests.js.snap
packages/apollos-ui-onboarding/src/Onboarding/index.js
packages/apollos-ui-onboarding/src/OnboardingSwiper/index.js
packages/apollos-ui-onboarding/src/index.js
packages/apollos-ui-onboarding/src/onboardingStatus.js
packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.js
packages/apollos-ui-onboarding/src/slides/AskName/AskName.js
packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotifications.js
packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.js
packages/apollos-ui-onboarding/src/slides/Features/Features.js
packages/apollos-ui-onboarding/src/slides/Follow/Follow.js
packages/apollos-ui-onboarding/src/slides/Follow/FollowConnected.js
packages/apollos-ui-onboarding/src/slides/Follow/__snapshots__/Follow.tests.js.snap
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.tests.js
packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap

test with `onboarding` branch in templates

chore: move onboarding to core

---

package.json
scripts/setup-api.sh
scripts/setup-app.sh

Try running `yarn app yarn`, or `yarn app start`

chore: Pass commands down when running yarn app/api

---

packages/apollos-ui-onboarding/src/index.js
packages/apollos-ui-onboarding/src/slides/Landing/Landing.js
packages/apollos-ui-onboarding/src/slides/Landing/Landing.stories.js
packages/apollos-ui-onboarding/src/slides/Landing/Landing.tests.js
packages/apollos-ui-onboarding/src/slides/Landing/__snapshots__/Landing.tests.js.snap
packages/apollos-ui-onboarding/src/slides/Landing/index.js
packages/apollos-ui-onboarding/src/slides/index.js

chore: move landing screen to core

---

packages/apollos-cli/index.js
packages/apollos-cli/package.json
packages/apollos-cli/scripts/secrets.sh
yarn.lock

from the apollos cli directory 
`npm exec apollos-cli secrets -d (whatever)` 
or 
- from apollos-cli `npm link` 
- from templates/apollos-church-api `npm exec apollos-cli secrets -d (whatever)`

chore: Apollos CLI package

---

packages/apollos-data-connector-postgres/src/content-items/dataSource.js
packages/apollos-data-connector-postgres/src/content-items/index.js
packages/apollos-data-connector-postgres/src/content-items/migrations/001_create_content_items.js
packages/apollos-data-connector-postgres/src/content-items/migrations/index.js
packages/apollos-data-connector-postgres/src/content-items/model.js
packages/apollos-data-connector-postgres/src/index.js

feat: Content Item Schema

---

packages/apollos-ui-connected/src/FeaturesFeedTabConnected/FeaturesFeedTabConnected.js

feat: add ability to pass options to FeaturesFeedTabConnected route

---

packages/apollos-data-connector-postgres/src/content-items/migrations/003_add_parent.js
packages/apollos-data-connector-postgres/src/content-items/migrations/index.js
packages/apollos-data-connector-postgres/src/content-items/model.js

feat: Add parent id

---

packages/apollos-data-connector-postgres/src/features/migrations/002_unique_index_for_features.js
packages/apollos-data-connector-postgres/src/features/migrations/index.js

I realized this index would be really useful when building features with the shovel.

feat: Feature Unique Index migration

---

packages/apollos-data-connector-postgres/src/tags/migrations/003_create_tags_unique_index.js
packages/apollos-data-connector-postgres/src/tags/migrations/index.js

chore: Add tags unique index

---

packages/apollos-ui-connected/src/FeaturesFeedTabConnected/FeaturesFeedTabConnected.js

This should be all that is needed to add additional features back to the tabfeed

fix: additionalFeatures back to tabfeedconnected
