ApollosProject/apollos-apps

mobile/package.json
Sets the default iOS simulator to iPhone X when running `yarn ios` 💥
=> Default iOS simulator to iPhone X

mobile/src/ui/theme/defaultTheme.js, mobile/src/ui/theme/fontStack/index.android.js, mobile/src/ui/theme/fontStack/index.ios.js, mobile/src/ui/typography/UIText/UIText.stories.js, mobile/src/ui/typography/UIText/UIText.tests.js, mobile/src/ui/typography/UIText/__snapshots__/UIText.tests.js.snap, mobile/src/ui/typography/UIText/index.js
Fixes #21!
This adds a very basic UIText component that renders with system fonts. It only supports a bold (700) weight and italics in the regular font. Future expansion could support thin, light, and medium font family varieties. This component is intended for UI purposes only as a way to make standard UI components feel more native. `theme.typography.sans` and `theme.typography.serif` are branded and to be used in all other places that require expressing said brand.
=> 21 (part 5) Typography UIText

.travis.yml, api/package.json
Implements Now into our current CI.
This allows us to build a new version of our API with each PR and a main api help at https://apollos-church-api.now.sh.
=> Now CI implementation

packages/apolloschurchapp/appcenter-post-clone.sh
Currently, appcenter builds are failing due to two reasons:
1. A late change to #226 removed `yarn.lock` files from our submodules. This is good for yarn workspaces, but appcenter.ms relies on this `yarn.lock` file to exist to detect whether to use yarn or npm. So, during our `pre-build` phase on appcenter, we now copy over a yarn.lock file for it to use.
2. appcenter keeps defaulting the selected `package.json` to the root-level `package.json` (even though there's a setting to change it - it's not saving it). I believe this is a bug on appcenter, and have contacted their support team for help. If they acknowledge that it's a bug, and will fix it, we might be forced to build manually for the short term. If not, I'll have to come up with another solution that I will address in this PR. …
=> Fix appcenter builds

packages/apolloschurchapp/android/app/src/main/AndroidManifest.xml
=> Fixed android builds by removing duplicate launchMode definition 

packages/apollos-church-api/src/data/content-items/index.js
Lets temporarily disable themes on the API side. We know the theming system now works, and we can re-implement once we have color values in Rock.
=> Disable themes on the api side (temporary), removes wild colors seen in app

.dockerignore, Dockerfile
I forgot to setup Docker with the new rock-apollo-data-source-package. This configures the Dockerfile so it copies over the package into the correct folder.
These packages should be automatically included. This is a temporary fix so we can deploy again, but we should be able to automatically include new packages using a file glob or something similar. 
`docker build --no-cache="true" -t apolloschurchapp .`
n/a
**Manual QA**
=> Fixes new package data source package not included in docker build

packages/apollos-church-api/package.json, yarn.lock
I added this package to help `babel-node` stop leaving ghost processes, but it breaks the docker container. If you still are running into issues with ghost processes, you can `yarn global add kexec` 
**Manual QA**
=> Remove kexec to fix docker builds

package.json
Improves the nuke script by not using lerna to delete node_modules folders. This makes sure we are actually clearing any left over node_modules folders from switching branches, and the root-level folder.
**Manual QA**
=> tweak nuke scripts to better remove `node_modules` folders

packages/apolloschurchapp/src/ui/LikeButton/LikeButton.tests.js, packages/apolloschurchapp/src/ui/LikeButton/index.js
Discovered in the Christ Fellowship app, if a ContentItem appears first as a sibling content item, and is tapped on the by the user, and that item has not appeared in the app before, the app throws an error. We need to provide a default safe value for `__typename` to fix this issue.
n/a
Can't reproduce in the ApollosChurchApp because all content items are included in the home query and are thus already cached. 
n/a
**Manual QA**
=> Fixes Unseen Content Like Button Crash

packages/apollos-church-api/src/data/index.js, packages/apollos-church-api/src/data/oneSignalWithRock.js, packages/apollos-data-connector-onesignal/src/__tests__/resolver.tests.js, packages/apollos-data-connector-onesignal/src/data-source.js, packages/apollos-data-connector-rock/src/index.js, packages/apollos-data-connector-rock/src/personal-devices/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/personal-devices/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/personal-devices/data-source.js, packages/apollos-data-connector-rock/src/personal-devices/index.js
Rock needs some record of a PersonalDevice in order to create the communication transport in Rock. This PR does two things:
- Adds a PersonalDevice data source to write to the PersonalDevice table.
- Adds a resolver override to attach the PersonalDevice rock specific code to the OneSignal specific code. 
I didn't want to add Rock specific code to the OneSignal Source, nor add OneSignal code to the Rock source, so I created a "resolver override" that fires off the OneSignal function first (which updates a value in Rock), and then fires the Rock function to add a PersonalDevice to Rock for a user. 
n/a
Hard to test before client front end is merged. I tested manually by ...
1. Login via graphql playground and get a token.
2. Check for your player ID in the OneSignal player list
3. called …
=> Adds PersonalDevices dataSource and attaches PersonalDevices to OneSignal.

packages/apollos-church-api/src/server.js
ApolloServer does this by default, but not when you use `applyMiddleware`. This unintentional change in configuration has caused headaches, and mounting on root will reproduce the same configuration as ApolloServer.
**Manual QA**
=> Mounted ApolloServer on root path

packages/apollos-data-connector-rock/src/campuses/__tests__/__snapshots__/resolver.tests.js.snap, packages/apollos-data-connector-rock/src/campuses/__tests__/resolver.tests.js, packages/apollos-data-connector-rock/src/campuses/data-source.js
When getting campuses for the current user, I wasn't expanding the location object so `lat` and `long` were returning null. 
This PR causes the `location` object to be expanded, so now you can get `lat` and `long` from the user's campus.
**Manual QA**
=> Fixes user campus not returning location

packages/apollos-church-api/src/server.js
a PR was added that mounts graphql at the root, which turns out broke pass generation. This PR reverses that change.
can no longer access graphql at `/`
**Manual QA**
=> undo mounting graphql at root to fix pass generation

packages/apolloschurchapp/src/notifications/NotificationManager.js
Currently, the app would prompt for notification permission at launch. We now handle this in onboarding so we can disable it. 
Disables the onesignal auto prompt.
N/A
Delete and reinstall the app on iOS and launch. You shouldn't get the notifications prompt until you ask for it in onboarding.
N/A
**Manual QA**
=> Removes the default/automatic notifications prompt on iOS

packages/apollos-ui-kit/src/Chip/index.js, packages/apolloschurchapp/src/ui/Onboarding/Slide/index.js, packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.js
Bye bye, annoying warning we would see all the time in onboarding. This was actually caused by the `Chip` component used in the `DatePicker` component and if you used `Chip` with the `icon` prop it would render two components and throw this error.
All this does is use `<></>` fragments inside `Chip` and 💥 we're good.
N/A
Open onboarding and you shouldn't see any warnings anymore. Specifically one related to rendering an array but expecting a single react element.
N/A
**Manual QA**
=> Fixs Chip component prop warning that was noticed on onboarding

packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
`react-native-custom-tabs` was never "unlinked" on iOS. This unlinks it.
nada
Make sure xcode builds. we never used custom-tabs on ios anyways.
n/a
**Manual QA**
=> unlink react-native-custom-tabs on ios

packages/apollos-church-api/src/data/index.js, packages/apollos-data-connector-rock/src/binary-files/__tests__/__snapshots__/binary-files.tests.js.snap, packages/apollos-data-connector-rock/src/binary-files/__tests__/binary-files.tests.js, packages/apollos-data-connector-rock/src/binary-files/data-source.js, packages/apollos-data-connector-rock/src/binary-files/index.js, packages/apollos-data-connector-rock/src/binary-files/resolver.js, packages/apollos-data-connector-rock/src/index.js, packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/people/data-source.js
The person resolver needs to fetch an image for a person if the URI is not provided on the data returned in the root. A common issue when fetching lists of people. Requested by @IsaacHardy in #697 
While writing this feature, I took an opportunity to create a BinaryFiles dataSource, which should make it easier for NS and future teams to handle uploading/fetching photos in future repos.
This PR covers the file uploading code, so be sure to visit the connect tab and upload a new profile pic.
100% test coverage
**Manual QA**
=> Adds binary files datasource

packages/apollos-data-connector-rock/src/personal-devices/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/personal-devices/data-source.js
Rich ran into this issue when building out push support in Rock. Apparently newer versions of Rock have this as a required field. Older versions of Rock will accept this new "IsActive" field and safely ignore it. 
1. Open the app with a new device. (could be a new sim) 
2. Go through onboarding
3. Accept push notifications
4. Make sure you have a personal device listed in rock (and you don't see any failures in the server log)
**Manual QA**
=> Fixes personal devices "post" by providing required rock field

packages/apollos-apollo-server-env-mock/src/apollo-datasource-mocks/bible.js, packages/apollos-data-connector-bible/src/data-source.js
Fixes our Bible.API usage to match current standards. I'm not sure why this broke, but it broke recently. I can't think of a way we could have anticipated this change, nor can I find reference to this change on bible.api's site 🤷‍♂ 
1. `yarn install`
2. Run the following query in Apollo
```
{
scriptures(query: "1 John 3:16, Romans 6:6"){
id   
html
}
}
```
Used existing automated tests.
**Manual QA**
=> Updates bible.api usage to match current practices

packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js, packages/apollos-rock-apollo-data-source/src/__tests__/request-builder.tests.js, packages/apollos-rock-apollo-data-source/src/request-builder.js
**Calling `getById` with no ids should always return an empty array**
Because the user hadn't liked any content, the resolver assumed that the user had liked ALL the content. This resulted in an error on the `getLikedContent` query when the user hadn't liked any content, due to an assumption being made about the length of the `following` array and the `contentItem` array in the resolver 
n/a 
1. Unlike all content.
2. Refresh the app.
3. Visit the Connect tab, make sure you don't see any liked content.
4. Like some content.
5. Visit the Connect content tab, make sure you see the content you liked.
Unit tests over new dataSource logic. 
**Manual QA**
=> Fixes Liked Content Feed not populating on first like. 

packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeader.test.js.snap, packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeaderConnected.tests.js.snap, packages/apolloschurchapp/src/ui/UserAvatarView/AvatarForm.js
Adds margin back to the user settings avatar that we lost when we refactored the `Avatar`.
None.
1. Boot up and look at the connect tab
2. `yarn test`
None.
**Manual QA**
=> Fixes Avatar Margin

packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.js, packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.tests.js, packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap, packages/apollos-ui-onboarding/src/slides/AskName/AskNameConnected.js, packages/apollos-ui-onboarding/src/slides/AskName/AskNameConnected.tests.js, packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap, packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.js, packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.tests.js, packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap, packages/apollos-ui-onboarding/src/slides/Features/FeaturesConnected.js, packages/apollos-ui-onboarding/src/slides/Features/FeaturesConnected.tests.js, packages/apollos-ui-onboarding/src/slides/Features/__snapshots__/FeaturesConnected.tests.js.snap, packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js, packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.tests.js, packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap
> "Our coding architecture encourages simple modular pure components that can be reused that are "driven by a ConnectedComponent. Currently connected components are hardcoded and tied to render their pure "child" component that they fetch data for. This makes it impossible to reuse them or customize the rendered child while keeping the ConnectedComponent unchanged resulting in unnecessary copy/paste and code debt." – #774 
This PR adds a `Component` prop to all of the onboarding ConnectedComponents.
None. All of the ConnectedComponents just default to the components they previously were rendering as children.
Open app launch onboarding. Everything works? Your good!
The new `Component` prop has 100% snapshot coverage 💥
**Manual QA**
> The purpose of …
=> Adds Component prop to ConnectedComponents in Onboarding

packages/apollos-data-connector-rock/src/content-items/data-source.js
Changes the algorithm for finding the parent images of Rock content slightly. Specific to instances where a piece of content has multiple parent content channels (campaign and sermon series). It’s looking at the _first_ parent to get images from. So it will fail if this is ever the case:
1. campaign -> no images
2. sermon series
None.
Make sure images show up correctly on multiple different types of content, including ones that have multiple parents.
None.
**Manual QA**
=> Fixes Parent Image Algorithm

packages/apollos-data-connector-rock/src/people/resolver.js, packages/apollos-rock-apollo-data-source/src/__tests__/data-source.tests.js, packages/apollos-rock-apollo-data-source/src/index.js
"Rock" was returning `{}` for values that were actually `null`. Turns out we were treating `null` as an object to be traversed, causing this issue. 
n/a
Check the automated tests. Should be no changes in how the API serves data. Endpoints that were doing manual checking of null values won't have their implementation change. 
Wrote a test to cover the `normalizer` in the Rock Apollo Datasource.
**Manual QA**
=> Fixes rock-apollo-datasource null bug

packages/apollos-church-api/local.graphql, packages/apollos-data-schema/src/index.js
I have found that having attributes marked as required can be brittle, for example, parts of our app now throw errors if you don't put in a first name on onboarding. Technically a first name is not great, but GraphQL shouldn't be throwing errors just trying to query for it.
Removes the required marker from `attributes` on types in the schema that have the marker. 
Schema no longer reflects "base case scenario" for data cleanliness as closely. 
1. Boot the app, it shouldn't fail.
2. Create a new user and opt to avoid setting a first name. The app will no longer throw an error.
n/a
**Manual QA**
=> Remove required flag from certain schema attributes 

packages/apollos-church-api/config.yml, packages/apollos-church-api/local.graphql, packages/apollos-data-connector-church-online/src/__tests__/__snapshots__/resolver.tests.js.snap, packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js, packages/apollos-data-connector-church-online/src/data-source.js, packages/apollos-data-connector-church-online/src/resolver.js, packages/apollos-data-connector-rock/src/content-channels/__tests__/resolvers.tests.js, packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap, packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js, packages/apollos-data-connector-rock/src/content-items/resolver.js, packages/apollos-data-schema/src/index.js
This PR adds some API functionality so that LiveStreams can be associated with ContentItems. Per discussion with @FrankGrand, the following logic is used to determine if a content item has a "live" livestream. 
- If the stream isn't currently live, no content items are live.
- If the stream is live
- The content item is live if the content item is the most recent sermon content item
- The content item is **not** live if there are more recent sermon content items than the current content item.
I also attach the `webViewUrl` and a `VideoMedia` to the livestream type.
- I chose to enhance the API design of the ChurchOnline resolver, by moving most functionality to the dataSource. 
- I added a new attribute to the config.yml for the content channel that holds your sermons.
- I added the …
=> Adds API support for content items to have livestreams

packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/index.tests.js.snap, packages/apollos-data-connector-rock/src/auth/data-source.js, packages/apollos-data-connector-rock/src/auth/token.js, packages/apollos-rock-apollo-data-source/src/index.js, scripts/watch.js
User's were occasionally getting logged in as the Apollos user. The issue was that if a user's cookie was bad (potentially expired by rock?) the auth token was still being sent to Rock. The auth token belongs to the apollos user, so the apollos user was being sent as the current user. 
n/a
We still need a PR that logs users out if they receive a AuthenticationError on the front end. 
@conrad-vanl tested via deploying this to Heroku
Updated existing snapshots. 
**Manual QA**
=> Auth issues

packages/apollos-data-connector-rock/src/content-items/data-source.js
Currently if a summary comes back starting with a number and a period, our natural language tokenizer splits on that number alone, this includes whatever follows that number.
None
Check the `userFeed` query or boot up the app, the "10 ways" content should now show a good summary.
None
**Manual QA**
=> Adds Check Against Short Content Summaries

packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.stories.js, packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.tests.js, packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap, packages/apollos-ui-kit/src/FeaturedCard/index.js, packages/apollos-ui-kit/src/HighlightCard/HighlightCard.stories.js, packages/apollos-ui-kit/src/HighlightCard/HighlightCard.tests.js, packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap, packages/apollos-ui-kit/src/HighlightCard/index.js, packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap, packages/apollos-ui-kit/src/theme/icons/PlayOpaque.js, packages/apollos-ui-kit/src/theme/icons/index.js
The props for `FeaturedCard` and `HighlightCard` did not match `ContentCard`. This updates them so that all three card components have the same API and in theory could use the same `ConnectedComponent`. 
This also sneaks an update into `HighlightCard` by adding and using the correct `PlayOpaque` icon for that card.
None! All of @michael-riddering's subtle design differences are acknowledged and faithfully upheld.
Stories are present to show these prop changes still work.
100% coverage.
**Manual QA**
=> Standardizes FeaturedCard, HighlightCard, and ContentCard prop naming

packages/apolloschurchapp/src/tabs/connect/Connect.js, packages/apolloschurchapp/src/user-settings/index.js
Currently, when logging out, the user is taken to a new version of the connect tab that hides user details. The user can still click around inside the app. 
Seeing as the is taking a more "logged in focused" experience, when a user logs out we should take them straight to the log in page so they have a chance to login again. 
1. Login.
2. Logout.
3. You should be taken to the Auth screen, rather than the connect tab. 
n/a
**Manual QA**
=> Adds Navigating to auth when logging out

packages/apolloschurchapp/src/user-settings/Locations/MapView.js
Fixes issue where the wrong campus would be a selected, if a user's location was received and new data was fetched after the map rendered, and the user never interacted with the campus selector. 
This was due to `this.state.campuses` never been updated with the new "index 0" campus. Removing campus from state and calculating the current campus on the fly fixes this issue. 
n/a
1. Open the location finder from a geolocation close to either Dallas or North Carolina 
2. Watch as the first campus card (cincinnati) changes to either Dallas or Anderson
3. Click the select campus button
- your sellected campus should be either dallas or anderson (whatever you are closest to)
n/a
**Manual QA**
> The purpose of PR Review is to _improve the quality of the …
=> Fixes wrong campus being selected under certain conditions

packages/apolloschurchapp/src/content-single/NavigationHeader.js
|![2019-08-02 13 47 25](https://user-images.githubusercontent.com/1637694/62388849-63db0f80-b52c-11e9-9d2d-df2f5cd61000.gif)|
|----------------------------------------------------------|-----------------------------------------------------------|---|
The back and close button currently do the same thing when looking at nested content cards. This PR fixes that by calling the correct functions from `ReactNavigation`, and removing some complexity along the way. 
n/a
1. Open a nested devotional, like the jeremiah series. 
2. Click a few layers deep, then try and exit
3. Click a few layers deep, then try and go back.
n/a
**Manual QA**
=> Fixes Back/Close doing the same thing inside devotionals

packages/apollos-data-connector-rock/src/features/data-source.js
Fixes this issue: 
`first` returns `null` or an item. `top` returns a cursor. We want the cursor. 
**Manual QA**
=> Fix using first instead of top in sermon children algorithm

packages/apollos-church-api/config.yml, packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js, packages/apollos-data-connector-rock/src/features/data-source.js, packages/apollos-data-connector-rock/src/features/resolver.js
Changes the configuration of the home features from being statically defined in a resolver, to being dynamically assigned inside the config.yml. The format is still not documented, and you may need to override the resolver anyway in order to add advanced features, but this way users will be able to edit the "core" configuration easily without needing to change code. 
n/a
1. Open the app.
2. Check the content on the home feed.
Existing automated tests pass. 
**Manual QA**
=> Adds easy configuration options for bulletin list. 

package.json
All test stages currently are running generate-snapshots and an additional build needlessly, because `prepublish` runs both on `install` and on `publish`. Using `prepublishOnly` limits the command to run on `publish` only, which is the intended behavior. 
n/a
Check that the build time is less than the average build time (might only be like 30 seconds, but hopefully more!)
all of them
**Manual QA**
=> Configs tests to only run story generation when actually publishing

packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
This PR should stop the emails we get from Apple telling us that we're missing things in our `info.plist`.
N/A
You really can't. I guess just merge it and then see if the Apple emails remove the `info.plist` warnings.
N/A
**Manual QA**
=> Fixes Apple Email Warnings

packages/apollos-church-api/config.yml, packages/apollos-church-api/src/server.js
This gives visibility to the Apollo Engine configuration. Technically, this has no effect on deployed environments because the variables are pulled automatically. But I think this is still valuable to partner churches for self-documenting what's happneing. And also allows a developer to create their own environment variant just by defining the `.env` variable. For example, I could specifiy `ENGINE_SCHEMA_TAG=michael` and get data on that variant without exporting the variable to my shell.
I added this to our code, not knowing that Apollo does it automatically but think it still is not a bad idea to leave it in. We'll ultimately match our API to whatever core decides.
**Manual QA**
> The purpose of PR Review is to _improve the quality of the …
=> Adds Explicit Apollo Engine Config

packages/apollos-data-connector-redis-cache/src/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-redis-cache/src/__tests__/data-source.tests.js, packages/apollos-data-connector-redis-cache/src/data-source.js, packages/apollos-data-connector-rock/src/followings/data-source.js
- Changes the way Redis is loaded, so that it's only loaded if the REDIS_URL is set, and gives nice warnings if it's not (but only when the redis cache is used) 
- I never fixed some of the cachekeys on the server, so `likedCounts` weren't being cached correctly. Woops! 
n/a
Run the app with a `REDIS_URL` set in your .env and load the home feed, you shouldn't see any warnings. 
Run the app without a `REDIS_URL` set in your .env and load the home feed, you should see a number of warnings, but only when loading the home feed.
**Manual QA**
=> Removes Redis warnings and fixes cache keys for like counts

packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/resolver.tests.js.snap, packages/apollos-data-connector-algolia-search/src/__tests__/resolver.tests.js, packages/apollos-data-connector-algolia-search/src/resolver.js, packages/apolloschurchapp/src/tabs/discover/SearchFeed/index.js
Currently because of how we index, items that are deleted (or are in some other way invalid) can break search results. We don't have a good mechanism for clearing those bad items out at the moment they become invalid, so this PR adds some safety around how we retrieve those items. (Previously this would break all search results) 
n/a 
1. Search for a term
2. Delete one of the items in the results Rock
3. Search for the term in the app, the item should no longer show up.
Tests over new resolver functionality.
**Manual QA**
=> Fixes invalid nodes breaking search results.

packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js, packages/apollos-data-connector-rock/src/content-items/resolver.js
We are already doing this on Willow. This PR stores the result of `getCoverImage` in Redis, so that we don't have to fetch the parents for ContentItems that don't have a cover image each and every time we query. 
This PR also eager loads the content channel for a content item, and uses it to return the data present on a ContentChannel, if it exists. This will further eliminate the number of calls we make to rock when loading the home feed. 
Before this PR
After this PR
n/a
1. Load the home feed in the app in master, note the number of queries running.
2. Load the home feed in this PR. It should look the same, but you should see a significantly reduced number of queries ran, especially after the second request. 
Tests over new cache functionality. 
**Manual QA**
**Code Review: Questions to …
=> Cache coverImages and don't fetch ContentChannels if not needed to reduce home feed query count

packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap, packages/apolloschurchapp/src/content-single/getContentItem.js, packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap, packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap, packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap, packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap, packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap, packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
We don't use the like count in the content tile anymore. We should remove it from the query. 
n/a
1. Open the home feed.
2. Everything should render without issues. 
n/a
**Manual QA**
=> Removes like-count from content tile

packages/apollos-data-connector-rock/src/content-channels/__tests__/__snapshots__/model.tests.js.snap, packages/apollos-data-connector-rock/src/content-channels/__tests__/model.tests.js, packages/apollos-data-connector-rock/src/content-channels/data-source.js
Implements in apollos core a change already made to Willow Creek. This ensures content is sorted in the order defined in DISCOVER_CONTENT_CHANNEL_IDS. It does so by sorting the channels after fetching them.
I also added an early return in. I checked if DISCOVER_CONTENT_CHANNEL_IDS can be undefined; it can, so I simply returned the order that ROCK gave us, if that's the case.
1. Change the order of the IDs in DISCOVER_CONTENT_CHANNEL_IDS located in config.yml
2. Start your packager/sim AFTER this change
3. Navigate to the Discover tab
4. The order of the channels should reflect your changes
|Normal|Reordered|
|---|---|
|<img width="569" alt="Screen Shot 2019-10-28 at 2 34 54 PM" src="https://user-images.githubusercontent.com/29125070/67708826-33700980-f993-11e9-8be2-9d6c619785cf.png">|<img …
=> Order Content Channels

packages/apollos-ui-kit/src/Avatar/index.js
Moves the loading indicator for uploading a picture to what is normally the button to change a user's image (obviously, while the loading indicator is there, it is not a button). We did this because the loading indicator was very difficult (read: impossible) to see when placed overtop of the placeholder icon or white pictures. Moving it to the new location means it's visible regardless of the current status of the profile image.
See above.
1. Navigate to the settings screen
2. Change your profile picture
3. The loading spinner should replace the camera icon until the image has finished loading
**Manual QA**
=> Move Picture Loading Indicator

packages/apollos-church-api/config.yml, packages/apollos-data-connector-analytics/src/data-source.js
Adds a config.yml variable that, when disabled, allows ROCK analytics to be disabled. This should reduce the load on ROCK should a partner church choose not to implement ROCK analytics.
I did this in a very rudimentary way. There is likely a better way to do this.
1. On ln 60 of `/apollos-church-api/src/server.js` add the following code `console.log(dataSources().Analytics.interfaces);`
2. Restart your server; you should see an array with the RockInteractionAnalytics interface
3. In config.yml, change ANALYTICS.USE_ROCK to false
4. Restart your server; you should see an empty interfaces array
**Manual QA**
=> Add Configurability for ROCK Analytics

packages/apollos-data-connector-rock/src/auth/data-source.js
This PR attempts to prefetch the current user in the initialize step of the Auth Data Source. It doesn't always succeed as apollo server seems to prevent us from awaiting this. That means that occasionally the initialization will complete before other calls to getCurrentPerson, and in that one case, it will save calls to ROCK.
On a fresh build, try logging in or calling the auth mutation; you should see only one call to getCurrentPerson logged in your server
**Manual QA**
=> Prefetch the Current User

packages/apollos-data-connector-rock/src/auth/data-source.js, packages/apollos-ui-auth/src/buildErrorLink.js
Previously, if a user had an invalid cookie, they wouldn't get logged out of the app properly for two reasons: 
1. Invalid cookies don't throw a Authentication error, they throw a 500 error. 
2. Even when an authentication error was thrown, the `authToken` local storage state wasn't being cleared. 
Both of those issues are fixed in this PR. 
n/a
🤔
1. Change Auth Datasource to throw an Authentication error, and browse the app and make sure you get logged out? 
2. Hardcode a bad cookie in the client, make sure an Authentication error is thrown in Rock (rather than a 500 error) 
n/a
**Manual QA**
=> Actually logs users with bad cookies out of the app

packages/apollos-ui-analytics/src/Provider.js, packages/apollos-ui-analytics/src/index.js
Makes the server-side analytics optional. The variable should be passed as a prop to the analytics provider. If not passed, it defaults to `true`, which enables server-side analytics.
1. Pass false into the analytics provider and ensure that server-side analytics do not run. (I just put a log inside server analytics package)
**Manual QA**
=> Adds additional server analytics

packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/jobs.tests.js.snap, packages/apollos-data-connector-algolia-search/src/jobs.js
`Bull` has some best practices for reducing the number of connections being created. Now, a maximum of 4 connections per server will be made to Redis. 
n/a
1. Run the api locally.
2. have redis setup locally. 
3. run `redis-cli client list` 
4. You should see 5 clients connected (4 for the server + 1 for the `client-list` command)
**Manual QA**
=> Ensures that n+3 redis connections aren't created

packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/people/data-source.js
Trims any string fields related to user profile to ensure we don't get extra spaces. This is primarily in place to prevent users from entering unwanted spaces into their name.
Did this on the server so that we don't have to worry about changing it everywhere on the client.
1. In onboarding change your name to have several spaces in front
2. On the next screen,  you should see that it's been trimmed
**Manual QA**
=> Trim Profile Fields

packages/apolloschurchapp/src/tabs/connect/ActionTable/index.js
Easy one! Just removes the second "give" link on the connect screen.
1. Go to the connect screen and fail to find a second link :D
**Manual QA**
=> Remove second give link

.mergify.yml, packages/apollos-ui-kit/package.json, packages/apollos-ui-kit/src/inputs/DateInput/DateInput.stories.js, packages/apollos-ui-kit/src/inputs/DateInput/DateInput.tests.js, packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap, packages/apollos-ui-kit/src/inputs/DateInput/index.js, packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap, packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap, packages/apolloschurchapp/metro.config.js, packages/apolloschurchapp/package.json, yarn.lock
Users on willow were confused by the calendar modal on Android. The default modal doesn't make it clear that you can tap "2019" to jump straight to the year picker. This changes the style of the modal on android so that the options you have to change the date are more clear.
n/a
**Manual QA**
=> Use calendar spinner view on android by default

packages/apollos-ui-auth/src/BackButton.js, packages/apollos-ui-auth/src/Password/index.js, packages/apollos-ui-auth/src/SMS/Verification.js, packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap, packages/apollos-ui-auth/src/styles.js
The back button on the SMS Verification screen filled the full width of the screen. This PR adds a view to suppress the width of the BackButton component.
1. On the login screen, enter your phone number
2. Horizontally aligned with the back button at the midpoint of the width of the screen, tap; nothing should happen
**Manual QA**
=> Suppress Back Button Width

packages/apollos-church-api/local.graphql, packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/index.tests.js.snap, packages/apollos-data-connector-rock/src/auth/data-source.js
Previously you would be redirected to the Landing screen if you made an error when logging in. Now, we return a more accurate "UserInputError" when you don't give `authenticate` the correct details, and so the app doesn't redirect to auth like the way it does with an `AuthenticationError`
2. Select either SMS or Username / Password login
3. Enter an incorrect password / pin code and hit submit
4. Confirm you weren't redirected
5. Enter the correct password / pin and submit.
Captured by an existing snapshot. 
**Manual QA**
=> Fixes being redirected when entering a bad email/password/sms pin. 

packages/apollos-data-connector-bible/src/data-source.js
To avoid the 5,000 daily request limit set by API.bible, we want to start caching the requests we make to their API. To do this, we are going to use the apollo datasource inmemory cache, because it will capture uses of the scripture API no matter the source, and should be robust enough for our needs. 
The TTL is set to 1 day, because it seemed like a sane place to start. We can lengthen it if we run into no issues, and shorten it if we discover a disadvantage to having the cache length lower.
There's a rather decent way to test this PR. 
1. Open up the datasource for the `data-connector-bible`, then create a (postbin)[https://postb.in/]
2. Drop the link to the postbin into your local datasource
3. Run the following two queries multiple times in GQL
```
query getScripture { …
```
=> Adds caching to requests made to api.bible

packages/apollos-data-connector-rock/src/auth/data-source.js
Gage and I experimented with this code to try and pre-cache the current user as early as possible. The hope was that this would help (caching the user early enough to avoid more than one current user request) in more requests than it hurt (fetching the current user needlessly). This has proven to not be the case, however. Spot checking of the data shows that because the `initialize` method can't be called with the async keyword, the extra currentUser fetch never populates the cache in time.
2. Login
3. Browse around
4. Nothing should seem different
n/a
**Manual QA**
=> Removes auth prefetch cache attempt

packages/apollos-church-api/local.graphql, packages/apollos-data-connector-rock/src/auth-sms/__tests__/__snapshots__/index.js.snap, packages/apollos-data-connector-rock/src/auth-sms/__tests__/index.js, packages/apollos-data-connector-rock/src/auth-sms/data-source.js, packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/auth/__tests__/index.tests.js, packages/apollos-data-connector-rock/src/auth/data-source.js, packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/people/data-source.js, packages/apollos-data-connector-rock/src/people/resolver.js, packages/apollos-data-connector-rock/src/template/data-source.tests.js
We are going to update the auth flow to capture Gender and Birthdate. The Gender and Birthdate fields are currently possible to provide via the schema, but they are not processed correctly. We do some processing when running the "updateFields" mutation, but we don't do that same processing when registering. This PR extracts that field processing into a seperate method, and then calls that method when both registering and updating so that the fields are mapped correctly in both places. 
This also involves changing how we handle enums, because we now want to be able to to pass either integers or strings to the GraphQL layer and have them map to the `Gender` enum directly. This involved removing the static and brittle Gender enum resolver, and replacing it with a resolver on the …
=> Adds support for the auth register endpoints to properly accept Gender/Birthdate

packages/apollos-ui-connected/jest.setup.js, packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.tests.js, packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap, packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/__snapshots__/HorizontalLikedContentFeed.tests.js.snap, packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/__snapshots__/PlayButton.tests.js.snap, packages/apollos-ui-connected/src/SearchCardConnected/__snapshots__/SearchCardConnected.tests.js.snap, packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarConnected.tests.js, packages/apollos-ui-connected/src/UserAvatarConnected/__snapshots__/UserAvatarConnected.tests.js.snap
This PR stabilizes tests in `ui-connected` by mocking `Image.getSize` and `Animated.timing`. Hopefully this should reduce the amount of erratic failures that I am seeing in travis and locally. 
Run the tests locally, make sure they don't fail for you.
**Manual QA**
=> Ensure animated values are always the same in connected tests

packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
Don't try and run the onEndReached method when loading. If you don't have content (or the content is still loading) you get one of two different Red Screens. 
This is only an issue now, because previously this component wouldn't render at all when it was loading (rather than the correct, current behavior, of rendering a loading state). 
I tested this fix in Willow. You'll need to make sure you don't have any content cached in your app, then tap on items with children (Psalm 119 items are a good item on the home feed). 
Before this update, you'll get a crash about 70% of the time. You won't be able to reproduce the crash with the same item (because the item will no longer ever be loading, once loaded once) 
n/a
**Manual QA**
> The purpose of PR Review …
=> Fixes Horizontal Content Series Connected Crash when Loading

packages/apollos-ui-auth/src/LoginProvider.js
We successfully made sure this query wasn't cached in the schema, but we still need to make sure the client doesn't pull the data from it's own internal cache.
1. Register with a new email address.
2. Logout
3. Try to login with the email address from above. You should be able to login, instead of being forced through register again. 
n/a
**Manual QA**
=> Fixes being forced through register after you have already registered

packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.js, packages/apolloschurchapp/src/testing-control-panel/index.js
This gives us the ability to authenticate to Rock while using Safari or another external browser.
None.
There's a button in the testing panel.
None.
**Manual QA**
=> Adds Auth to External Browser

packages/apollos-ui-kit/src/styled/__snapshots__/styled.tests.js.snap, packages/apollos-ui-kit/src/styled/index.js, packages/apollos-ui-kit/src/styled/styled.tests.js
I wanted style overrides to be able to look at the component's props. It will make styling some crucial components (like radio buttons and other interactive styled elements) way easier. 
We now have functions stored in the theme, but we already have them anyway! So I think we're okay. 
Write yourself some overrides :) or look at the test I wrote.
Test demonstrating new functionality.
**Manual QA**
=> Adds capability to styled overrides; they can now be a function of component props

packages/apollos-data-schema/src/index.js, packages/apollos-ui-connected/src/ContentCardConnected/ContentCardConnected.js
Didn't realize this was GraphQL's behavior, but it makes sense 🤷‍♂ If a field isn't included in a response, then it's `maxAge` value is not respected for the returned result. 
Long term there's a better fix for this PR, but we'll need to be clever about it because it will cause breaking changes. 
1. Setup the `LiveStreams` query so that it _always_ returns content items, even if the `liveStream.isLive` is `false. 
2. Change the client LiveStream provider so that it uses the `true/falseness` of `LiveStream.isLive` rather than the presence of the item in the array. **I'll include that fix in this PR**. 
If we do step 1, without first deploying step 2, old versions of the app will display content as live perpetually. 
**Manual QA**
> The purpose of PR …
=> Decrease the cache time for the livestreams query

packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
Have been getting off-and-on errors navigating content and content children on The Porch App. Such as:
and 
Looking at network stacks, it appears that all queries were successful. I am unsure why `null` is being returned in this scenario yet, but it seems like something the UI should handle without throwing errors. Thoughts?
**Manual QA**
=> Safer handling of getting horizontal content item fetch more results

packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardConnected.js, packages/apollos-ui-connected/src/HorizontalContentCardConnected/index.js, packages/apollos-ui-connected/src/index.js
Adds export for horizontalContentCardComponentMapper to ui-connected package. We normally do this for all of our connected components so that the pieces that make up our connected components can be used to create new connected components. Not sure why we didn't do it to begin with but here it is now.
This PR is blocking https://github.com/ApollosProject/apollos-templates/pull/24
N/A
N/A
N/A
**Manual QA**
=> Adds export for horizontalContentCardComponentMapper to ui-connected package

package.json
When working with storybook and switching between branches there is no easy way to update storybook to know that files might have been added or removed. This just "complies" the list of stories with `yarn start` like we use to do.
Might take a fraction of a sec longer to run `yarn start` now.
`yarn start` and see that stories were complied.
**Manual QA**
=> Add command to update stories on yarn start

packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap, packages/apollos-ui-kit/src/inputs/Search/styles.js
This bug was introduced to support "dark mode" as a result I tested this in both dark and light theme types.
All this does is move the `color` style definition into the `style` object one line below it 💥
N/A
1. Open the app on android.
2. Tap on discover.
3. No crash? 🙌 
You're welcome to switch theme types to see how the text colors render if you want too.
None. This fix only concerns android and jest doesn't cover android 😢 
**Manual QA**
=> Fixes crash in search on android

packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/WebviewFeature.js, packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/__snapshots__/ContentSingleFeaturesConnected.tests.js.snap
Simply just changed the default color variable to `secondary` for the link in the Webview Feature header (Open in Spotify).
**Manual QA**
=> Default link text color to secondary on Webview feature

packages/apollos-ui-connected/src/SearchCardConnected/SearchCardConnected.tests.js, packages/apollos-ui-connected/src/SearchCardConnected/__snapshots__/SearchCardConnected.tests.js.snap, packages/apollos-ui-connected/src/SearchCardConnected/index.js
At present, items that don't have images don't show up, period, when they are a HighlightCard. I don't know the exact Root of this, I believe it's do to the logic with how the <Image> component is rendered. 
To fix, we need to do what the `ContentCardConnected` does and default a content item without an image to have a `coverImage` of `undefined`. 
This fix was successfully deployed on Grace.
n/a
Download Grace and search :)
New tests over new image state.
**Manual QA**
=> Ensure SearchCards without images still render

packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap, packages/apollos-server-core/src/node/model.js
Passes the schema info (optionally) to the `getFromId` method. This allows those `getFromId` methods to utilize the schema info, as well as granting them access to helpful methods like `info.cacheControl.setCacheHint({ maxAge: 60, scope: 'PRIVATE' });`
n/a
n/a
Updated snaps to include new arguments being passed.
**Manual QA**
=> Pass schema info to resolving methods

packages/apollos-ui-kit/src/StretchyView/StretchyView.stories.js, packages/apollos-ui-kit/src/StretchyView/index.ios.js
If you've ever noticed a bug in our apps where pulling down on a content-item causes the cover image to flash to gray - this fixes it!
This issue is caused by re-renders to the children you pass to `<Stretchy>` are not picked up. I hacked together a "clever" solution using `useEffect` and a deep-comparison on `children` to mitigate. It's....not super clean but it is succinct and I think fairly stable.
Before:
After:
Check out the story! Press the button.
**Manual QA**
=> Fix issue where re-renders aren't picked up in StretchyView

packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js, packages/apollos-ui-connected/src/CampaignItemListFeature/index.js, packages/apollos-ui-connected/src/ContentCardConnected/ContentCardComponentMapper/index.js, packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/WebviewFeature.js, packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeature/index.js, packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/index.js, packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/index.js, packages/apollos-ui-connected/src/LikeButtonConnected/LikeButton/index.js, packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/PlayButton.js, packages/apollos-ui-connected/src/ShareButtonConnected/ShareButton/index.js, packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarUpdate/UserAvatarUpdate.js, packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/index.js
The purpose of this PR is to make sure all instances of using `withTheme` and `styled` in core's ui-connected package provides a named override. With "names", church apps are able to override that component's style. For example:
```
const MyButtonOnCore = styled({
backgroundColor: 'green',
}, 'MyButtonOnCore')(Button);
```
And then in an app's overrides, you could override that button's styles:
```
const overrides = {
'MyButtonOnCore': {
backgroundColor: 'red',
}
}
```
=> Ui-connected override names

packages/apollos-ui-auth/src/BackButton.js, packages/apollos-ui-auth/src/Entry.js, packages/apollos-ui-auth/src/Header.js, packages/apollos-ui-auth/src/styles.js
The purpose of this PR is to make sure all instances of using `withTheme` and `styled` in core's ui-auth package provides a named override. With "names", church apps are able to override that component's style. For example:
```
const MyButtonOnCore = styled({
backgroundColor: 'green',
}, 'MyButtonOnCore')(Button);
```
And then in an app's overrides, you could override that button's styles:
```
const overrides = {
'MyButtonOnCore': {
backgroundColor: 'red',
}
}
```
=> Ui-auth override names

packages/apollos-eslint-config/web.js
The rule ` react/jsx-props-no-spreading` is either new or broken on for react native. I noticed it was throwing lots of errors on the web though. Either way we spread props in our library code a lot. So I'm turning it off on web for congruency. 
N/A
N/A
N/A
**Manual QA**
=> Aligns eslint web rules with core

packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
The funny thing is, this PR might completely eliminate the need to have the `CampaignCards` long term, we could have the CardMapper look at `isFeatured` instead. 
For what it's worth, we are doing this on Grace in order to use both a custom mapper and FeaturedCards
https://github.com/Differential/grace-apollos-app/commit/110e453015e0e9bf93bd8ab4187ee38a212a0e82#diff-33281eb9f3d40f3dcfa35a784630e994L14
https://github.com/Differential/grace-apollos-app/commit/110e453015e0e9bf93bd8ab4187ee38a212a0e82#diff-620a567ff291d601c67a71ba9238435dR47
**Manual QA**
=> Pass down isFeatured prop so CardMapper can identify FeaturedCards

ApollosStorybook/metro.config.js
Now sure when this started happening, but I've been getting a dependency error in the ApollosStorybook. This change to the `metro.config.js` stops `@storybook` from being loaded multiple times, and that stops `react-native` from being loaded multiple times. 
**Manual QA**
=> fix: Storybook bringing along RN dep

packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntry.js, packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntryConnected.js
This PR adds theme overrides to ProfileDetailsEntry and ProfileDetailsEntryConnected.
**Manual QA**
=> fix: Adds Auth theme overrides

packages/apollos-ui-mapview/src/MapView/index.js, packages/apollos-ui-mapview/src/MapViewConnected/MapViewConnected.stories.js
Scrolls the map view to the closest campus on load. 
Best place to test is the new `MapViewConnected` story,
**Manual QA**
=> fix: Scroll MapView to first campus on load

packages/apollos-data-connector-bible/src/__tests__/__snapshots__/resolver.tests.js.snap, packages/apollos-data-connector-bible/src/__tests__/resolver.tests.js, packages/apollos-data-connector-bible/src/data-source.js
Bible.API returns `data` with a different struture than we are expecting if the query was invalid. This just returns an empty array, signalling that something went wrong in the query.
**Manual QA**
=> fix: Fixes Incorrect Scripture Query

packages/apollos-data-connector-rock/src/feature-feeds/index.js, packages/apollos-data-connector-rock/src/features/data-source.js, packages/apollos-data-connector-rock/src/features/resolver.js, packages/apollos-data-connector-rock/src/index.js, packages/apollos-data-schema/src/index.js
This PR breaks out the `userFeedFeatures` query into `homeFeedFeatures` and `discoverFeedFeatures` and defines a new way to deterministically generate a feed of feeds. Look through the schema for details. Test with `feature-feed` branch in templates.
=> feat: Adds Discover Feed Query

package.json
We can't do them the other way because canaries only the minor version regardless of conventional tags so we'd never get a 1.7.0-beta
=> chore: Old fashioned beta releases

packages/apollos-data-connector-rock/src/rock-constants/__tests__/__snapshots__/rock-constants.tests.js.snap, packages/apollos-data-connector-rock/src/rock-constants/__tests__/rock-constants.tests.js, packages/apollos-data-connector-rock/src/rock-constants/index.js
Brian at Newspring found a bug that goes something like this: 
A new piece of content is published 
A user interacts with that content, we check to see if there's a component for it, see that there's not, and **cache the result of that call for 24 hours**
We then create a component for that content item. 
Another user interacts with that content, the cached result for the component is returned, and we create **another** new component. 
This continues for 24 hours passes and the cache clears (or until the server restarts). 
The fix that I've implemented is to ditch the apollo-datasource-cache and use the Redis cache, which gives me the control to ensure that we only cache created components, and never cache an empty state. 
**Manual QA**
> The purpose …
=> fix: Use redis cache for rock-constants code

ApollosStorybook/yarn.lock, packages/apollos-ui-kit/src/theme/__snapshots__/mixins.tests.js.snap, packages/apollos-ui-kit/src/theme/mixin.stories.js, packages/apollos-ui-kit/src/theme/mixins.js, packages/apollos-ui-kit/src/theme/mixins.tests.js
When using `ThemeMixin`, if you passed colors with null values, the ThemeMixin would pass down default colors **from core theme** instead of passing down colors **from the the user theme input**. 
We got around this a bunch of ways in the past, @conrad-vanl had a good fix that serviced a lot of our client apps, but I wanted to bring this fix into core and fix that "gotcha". 
Best way to test is run through the `mixin` stories I made. The colors you see should match the colors described in the text. 
**Manual QA**
=> fix: Stop ThemeMixin from clobbering ThemeInput

packages/apollos-data-connector-rock/src/action-algorithms/index.js, packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js
This will let us specify which series channels we want to look through for progress items. So instead of including all sermon series _and_ devotional series by default, we can pick one.
=> feat: Adds Whitelist to Series Progress Algorithm

.github/workflows/ci.yml
This matches what we do in templates and fits with Github best practices by showing the correct job name, helpful for the CLI
=> chore: Combines CI Workflow

packages/apollos-ui-kit/src/theme/createTheme.js, packages/apollos-ui-kit/src/theme/createTheme.tests.js
it was technically supported before, except that there was a slight bug where it would try to merge in using the previous ALL CAPS theme type, instead of merging in the validated and transformed lowercase theme type.
**Manual QA**
=> fix: Uppercase type support in create theme

packages/apollos-ui-kit/src/NavigationService/index.js
We need a way to interface with this new `onReady` callback, otherwise we fire events from deep links before navigation has fully mounted. 
Usage example: 
**Manual QA**
=> fix: Adds support for @react-navigation onReady callback

packages/apollos-ui-connected/src/NodeSingleConnected/index.js
Needed to add the sermon notes feature into Newspring without needing to copy the whole NodeSingleConnected component. This + `named` = 👍 
**Manual QA**
=> feat: Support swapping out NodeSingleInner component

packages/apollos-data-connector-postgres/src/comments/dataSource.js, packages/apollos-data-connector-postgres/src/user-flags/dataSource.js
Our first SQLite vs Postgres difference :) Sqlite ignores that we haven't cast these fields, Postgres gets mad. 
**Manual QA**
=> fix: Cast possible ints into strings when filtering

packages/apollos-data-connector-rock/src/feature-feeds/index.js, packages/apollos-data-schema/src/index.js
This is just to match the functionality of `WeekendContentItem`. We can deprecate content features later if we feel they are not the best method moving forward.
=> feat: add scripture features to devotional content items

packages/apollos-ui-connected/src/AddCommentFeatureConnected/__snapshots__/AddCommentFeatureConnected.tests.js.snap, packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.js, packages/apollos-ui-kit/src/AddCommentInput/__snapshots__/AddCommentInput.tests.js.snap
The AddComment Component was crashing because `Touchables` on Android can't have more than a single child. I refactored the component so that there's an inner view (containing the styles) 
**Manual QA**
=> fix: Add Comment Component Crashes on Android

packages/apollos-ui-connected/src/features/ScriptureFeature.js
From the `featureFeedComponentMapper` it sends the `featureId` prop, not either of two props the share button is expecting
=> fix: send feature ID to share button

packages/apollos-data-connector-rock/src/followings/__tests__/resolvers.tests.js, packages/apollos-data-connector-rock/src/interactions/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/interactions/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/interactions/data-source.js
This will allow us to remove an unneeded variable from the config yml. Not sure the original purpose of throwing the interaction data in there like that
=> chore: remove URL from interaction data

packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js, packages/apollos-data-connector-rock/src/events/__tests__/data-source.test.js
Don't really need this variable, it makes more sense and is served better from `APP.ROOT_API_URL`
=> chore: remove need for Rock share URL

packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntry.js
The "max" is 16 years ago. Previously it was trying to set the default to "today', and then snapping back to 16 years. Now, you'll be able to change your month and day before changing your year, while also not being able to select an age less than 16 years old. 
Visit the age selection in onboarding by using a new email when logging in.
=> fix: Correctly default date picker to 18 years ago

packages/apollos-ui-auth/src/Password/PasswordEntry.js, packages/apollos-ui-auth/src/Password/__snapshots__/PasswordEntryConnected.tests.js.snap, packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntry.tests.js.snap, packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntryConnected.tests.js.snap, packages/apollos-ui-auth/src/ProfileDetails/__snapshots__/ProfileDetailsEntry.tests.js.snap, packages/apollos-ui-auth/src/ProfileDetails/__snapshots__/ProfileDetailsEntryConnected.tests.js.snap, packages/apollos-ui-auth/src/styles.js
The next/submit button is no longer covered by the keyboard. 
Walk through the auth/onboarding flow. Aka - use an email or phone number you haven't used before.
=> fix: Button padding on Auth Onboarding

packages/apollos-ui-fragments/src/features.js
This will let us remove the need for including the comments schema before churches are ready for all the baggage that comes with the postgres data connector. This should be fine because we are already pulling the `id` above the specific types
=> fix: remove comment list query fragment

.github/workflows/ci.yml
We are not getting accurate Codecov reports because tests don't run on master
=> chore: run CI on branch pushes

packages/apollos-data-connector-postgres/jest.setup.js, packages/apollos-data-connector-postgres/jest.teardown.js, packages/apollos-data-connector-postgres/src/people/__tests__/model.js, packages/apollos-data-connector-postgres/src/postgres/index.js, packages/apollos-data-connector-postgres/src/postgres/test-connect.js
The unique index on the `originId` and `originType` allows us to do an "upsert" using those two fields. 
The UUID is how we'll be storing IDs moving forward.
=> feat: Add a unique index for origin fields and switch to uuid for ids

packages/apollos-ui-connected/src/ContentChildFeedConnected/__snapshots__/ContentChildFeedConnected.tests.js.snap, packages/apollos-ui-connected/src/ContentParentFeedConnected/__snapshots__/ContentParentFeed.tests.js.snap, packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap, packages/apollos-ui-kit/src/DefaultCard/index.js, packages/apollos-ui-kit/src/FeaturedCard/index.js, packages/apollos-ui-kit/src/HighlightCard/index.js, packages/apollos-ui-kit/src/theme/ThemeProvider.js, packages/apollos-ui-kit/src/theme/mixins.js, packages/apollos-ui-kit/src/theme/withTheme.js
WOW. That was enlightening.
This will allow us to pass a `theme` prop when using `withTheme` or `withThemeMixin`. I think there's definitely room to overhaul our theming system to remove the vast assortment of HOCs we have available, they mostly do the same thing in a slightly different way.
=> fix: allow theme HOCs to accept custom theme prop

packages/apollos-data-connector-rock/src/__snapshots__/sanitize-html.tests.js.snap, packages/apollos-data-connector-rock/src/sanitize-html.js, packages/apollos-data-connector-rock/src/sanitize-html.tests.js
The `sanitize-html` pkg was converting `null` to `"null"`. This will return an empty string instead
=> fix: return empty string with null HTML

packages/apollos-ui-mapview/src/MapView/index.js
Happens because when a user location is added, the `currentCampus` becomes `[]` and current campus stays as the current campus. It's a funky edge case, and checking for loading fixes it. 
1. Delete and reinstall the app
2. Boot the app and visit the user settings screen
3. Select Location, approve the request for location permission.
=> fix: crash when setting user location

packages/apollos-data-connector-postgres/src/people/dataSource.js, packages/apollos-data-connector-postgres/src/people/model.js
Keeps track if a user is an apollos users (as opposed to a user shoveled from a CMS)
=> feat: Add apollosUser database attribute

packages/apollos-data-connector-postgres/src/comments/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/postgres/__tests__/index.js, packages/apollos-data-connector-postgres/src/postgres/index.js, packages/apollos-data-connector-postgres/src/user-flags/__tests__/dataSource.js
We opted to make the apollos ids `${typename}:{database_uuid}`. The shovel does this by default, but your API still was using a different strategy. 
Easiest way to test is add some comments and check their ID. 
```
mutation addComment {
addComment(parentId:"WeekendContentItem:f8460101368b38c5aa9bbea8b2b8a625", text:"testing this stuff out :) today 2", visibility:PUBLIC){
id
}  
}
```
=> chore: Use Postgres uuids wherever possible

packages/apollos-data-connector-postgres/src/comments/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/comments/__tests__/resolver.js, packages/apollos-data-connector-postgres/src/comments/dataSource.js, packages/apollos-data-connector-postgres/src/comments/model.js, packages/apollos-data-connector-postgres/src/comments/resolver.js, packages/apollos-data-connector-postgres/src/follows/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/follows/dataSource.js, packages/apollos-data-connector-postgres/src/people/dataSource.js, packages/apollos-data-connector-postgres/src/user-flags/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/user-flags/dataSource.js, packages/apollos-data-connector-postgres/src/user-flags/model.js
Gets rid of the "external user id" notion, and uses the postgres primitives for a table join. One of those things that we couldn't easily do if we were in production, but thankfully we're technically not :) 
Here's my set of test mutations, but you can also test by clicking around and adding comments in the app. No change in actual functionality. 
```
query content {
contentChannels {
childContentItemsConnection {
edges {
node {
id
... on FeaturesNode {
featureFeed {
features {
... on CommentListFeature {
id
}
}
}
}
}
}
}
}
}
query commentListFeature {
node(id:"CommentListFeature:f5f25daa33b6f865b2f0d38f199b8de9dbaac83c6efefefeb49da137258038333a3794da043a4ca891c2f3ff182f33ca9dc2869613cc5bae845ecbe13347e517"){
id
... on CommentListFeature {
id
comments {
id
person {
firstName
lastName
} …
```
=> chore: Refactor Comments model to point directly at the postgres people table

packages/apollos-data-connector-postgres/src/people/resolver.js, packages/apollos-ui-connected/src/AddCommentFeatureConnected/AddCommentFeatureConnected.js, packages/apollos-ui-connected/src/AddCommentFeatureConnected/__snapshots__/AddCommentFeatureConnected.tests.js.snap, packages/apollos-ui-connected/src/AddCommentFeatureConnected/addComment.js, packages/apollos-ui-connected/src/CommentListFeatureConnected/CommentListFeatureConnected.js, packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.js, packages/apollos-ui-kit/src/AddCommentInput/__snapshots__/AddCommentInput.tests.js.snap
- The private/public flag on the create comment screen now actually does something
- the names of commenters are now showing up again, we had to reimplement the `nickName` field on the postgres person datasource
- Flagging a comment now immediately removes it from the comment list. It might show up again if the server is set to allow for more than one flags, but that's okay for now.
=> fix: Upgrades and fixes for comments

packages/apollos-ui-connected/__mocks__/react-native-safe-area-context.js, packages/apollos-ui-connected/src/ConnectScreenConnected/ConnectScreenConnected.tests.js, packages/apollos-ui-connected/src/ConnectScreenConnected/__snapshots__/ConnectScreenConnected.tests.js.snap, packages/apollos-ui-connected/src/ConnectScreenConnected/index.js, packages/apollos-ui-connected/src/FollowListConnected/RequestedFollowListConnected.js, packages/apollos-ui-connected/src/FollowListConnected/SuggestedFollowListConnected.js, packages/apollos-ui-connected/src/UserAvatarHeaderConnected/UserAvatarHeader.js, packages/apollos-ui-connected/src/UserAvatarHeaderConnected/UserAvatarHeader.tests.js, packages/apollos-ui-connected/src/UserAvatarHeaderConnected/__snapshots__/UserAvatarHeader.tests.js.snap, packages/apollos-ui-connected/src/UserAvatarHeaderConnected/getUserProfile.js, packages/apollos-ui-connected/src/UserAvatarHeaderConnected/index.js, packages/apollos-ui-connected/src/index.js
Two things 
- Adds pull to refresh to the connect tab. Uses a similar strategy as the featureFeeds to refetch multiple children components. 
- Moves the connect tab to a `ConnectScreenConnected` component. Gasp. I might be jumping the horse a bit on this one, but I think it's a start in the right direction. Removes a ton of code from templates: https://github.com/ApollosProject/apollos-templates/pull/291
Clone the companion PR (https://github.com/ApollosProject/apollos-templates/pull/291). Visit the connect tab. Pull to refresh. You should see your API console register the pull and show you a few queries running (I have a gif on my work computer)
=> feat: Pull to refresh on the connect tab

.github/workflows/release.yml
`sed` is behaving differently, breaking some of our bash scripts
=> chore: use macOS for version bump

packages/apollos-data-connector-postgres/src/people/migrations/003_add_names_index.js, packages/apollos-data-connector-postgres/src/people/migrations/index.js, packages/apollos-data-connector-postgres/src/postgres/migrations/001_add_pg_trgm_extension.js, packages/apollos-data-connector-postgres/src/postgres/migrations/index.js, packages/apollos-data-connector-postgres/src/postgres/performMigrations.js
Speed up searching by full name in the people table.
This adds an index on `lower("firstName" || ' ' || "lastName")` to allow efficiently searching via full name like "Jimmy Hogoboom". Note that the input search term will need to be made lowercase ("jimmy hogoboom").
Try running `EXPLAIN ANALYZE SELECT "firstName" || ' ' || "lastName" FROM people WHERE lower("firstName" || ' ' || "lastName") LIKE '%vincent wilson%'` before and after applying this PR to see the speed difference.
=> chore: Add GIN name index to optimize searching by name

packages/apollos-data-connector-onesignal/src/data-source.js, packages/apollos-data-connector-postgres/src/follows/__tests__/__snapshots__/dataSource.js.snap, packages/apollos-data-connector-postgres/src/follows/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/follows/dataSource.js, packages/apollos-ui-connected/src/index.js, packages/apollos-ui-notifications/src/Provider.js
Companion PR here: https://github.com/ApollosProject/apollos-templates/pull/296
This is a fun one ... 
Adds in a check for the `actions` that OneSignal sends over, and then lets users provide a custom function to fire when an action matches a passed prop. You can see that being used here: 
https://github.com/ApollosProject/apollos-templates/pull/296/files#diff-9b1509d1d4517465bef7cbb0733f3cf179f1e9b555e50041214d2103218846e6R21-R28
Also adds a call to onesignal to send a notification when a user requests to follow another user. That part is straightforward.
This is what I did.
1. Clone this PR and it's companion. you need to have a database_url and run postgres.
2. Triple check your env variables. You should have an OneSignal api key and id in your api, and a matching one signal id in your …
=> feat: Push notifications on follow request

packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
`id` is undefined in the loading state, causes a warning every time
=> chore: make action list id prop optional

packages/apollos-ui-prayer/src/PrayerFeature/index.js
was throwing a warning in the loading state
=> chore: make prayers prop optional

packages/apollos-ui-connected/src/ConnectScreenConnected/index.js
This functionality was behaving oddly because of my invalid use of `hooks`. The `refetchFunctions` state was `{}` for both calls to `refetchRef`  most of the time the component was rendered, and so the last child to call `refetchRef` would be the only `refetch` set
The functionality below more closely mimics what we do in `FeaturesFeedConnected`
=> fix: Pull to refresh not working consistently

packages/apollos-ui-connected/src/AddCommentFeatureConnected/addComment.js
This broke when we added this `isLiked` field to the comment query. We need to make sure we have it in the mutation, so we can safely insert the comment into the comment list cache.
=> fix: Restore optimistic updating for add comment

packages/apollos-data-connector-postgres/src/people/resolver.js
We are now saving `nickName` to the `firstName` field using the shovel, so the nickName field should be just `firstName` (and probs deprecated some time soon)
=> fix: Map nickName to firstName

.github/workflows/release.yml
Currently, the first canary after the release fails because there's already a `.0`. This should be fine even if the version number doesn't reflect the conventional commits version, we only to need to make sure the canary is the latest possible code, version number is irrelevant
=> chore: publish canary before stable release

packages/apollos-data-connector-rock/src/action-algorithms/index.js, packages/apollos-data-connector-rock/src/content-items/data-source.js
This PR accomplishes two things:
1. Decouples the search indexed content from the user feed. Sometimes you want to be able to search for more than just what's in the user feed.
2. Replaces two algorithms with one.
Test using the `feeds` branch on templates
=> chore: decouple search channels from user feed

.github/workflows/release.yml
I think what's happening is a foot race between the templates bump and the API propogating the tag they just received from us on the previous step
=> chore: delay templates bump in release

packages/apollos-data-connector-postgres/__mocks__/@apollosproject/config.js, packages/apollos-data-connector-postgres/src/follows/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/follows/dataSource.js
We need to open up to the connect tab since iOS user's don't get the cool button.
=> feat: Follower request push notification opens to connect tab

packages/apollos-ui-connected/src/NodeSingleConnected/index.js
Previously you could only set a custom `Component` if your node single had media. This is an edge case regression when the new media player was added
=> fix: component overrides for NodeSingleConnected

packages/apollos-data-connector-cloudinary/src/__tests__/cloudinary.tests.js, packages/apollos-data-connector-cloudinary/src/cloudinary.js
The Cloudinary settings we had were pretty liberal and can result in large images. This forces the fetch format to jpg which forces Cloudinary to make images lossy, and makes the base image size smaller. Because of this, we can get rid of the `eco` setting we previously had. 
The same image that is several megabytes on Newspring's instance is now ~150kb.
=> fix: Optimize Cloudinary image settings

packages/apollos-ui-kit/src/AddCommentInput/AddCommentInput.js, packages/apollos-ui-kit/src/AddCommentInput/Editor.js, packages/apollos-ui-kit/src/AddCommentInput/Navigator.js
For the editor window, the initial bottomSheetIndex was 0 (since the component was full screen).
=> fix: Buttons hiding too soon in editing modal on Android

packages/apollos-ui-notifications/src/Provider.js
This allows for passing a more complete external link handler that works well with the API link generation
=> chore: add new external link handler

packages/apollos-ui-notifications/src/pushProvider.js
We are already exporting the `PushContext`
=> chore: deprecate PushConsumer

packages/apollos-data-connector-rock/src/content-items/resolver.js
Not sure how I missed this the first time, this is going to break every time because it doesn't have what it needs for `resolveType`
=> fix: correctly gets content sharing url

packages/apollos-data-connector-postgres/src/people/__tests__/__snapshots__/dataSource.js.snap, packages/apollos-data-connector-postgres/src/people/__tests__/dataSource.js, packages/apollos-data-connector-postgres/src/people/dataSource.js
A hack to mask what is potentially an isolated but trickier problem to solve. If user exists in the context of `getCurrentPerson`, but doesn't in Postgres, we should log that user out. In the past, similar problems would fail silently but we'll need to raise an exception.
=> fix: Add an auth error if a user is not in Postgres

packages/apollos-bugsnag/src/index.js
uses `development` if localhost is in the URL, else `production`
=> chore: use default bugsnag release stage

packages/apollos-data-connector-rock/src/content-items/data-source.js
This uses the new \`ALL_CONTENT_CHANNELS\` variable for active content and search indexing
=> chore: remove redundant config variable

packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js, packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/data-source.test.js.snap, packages/apollos-data-connector-rock/src/groups/__tests__/data-source.test.js, packages/apollos-data-connector-rock/src/groups/data-source.js, packages/apollos-data-connector-rock/src/personal-devices/data-source.js
also removes the HUGE rock constants section that we've never had to touch, only 5 of the items are used anyway and in the extremely unlikely chance there's a change required, they could just overwrite the DS function.
=> chore: add group type defaults

packages/apollos-ui-auth/src/Password/PasswordEntryConnected.js, packages/apollos-ui-auth/src/Profile/ProfileEntryConnected.js, packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntryConnected.js, packages/apollos-ui-auth/src/SMS/PhoneEntryConnected.js, packages/apollos-ui-auth/src/index.js, packages/apollos-ui-kit/src/NavigationService/index.js
Cleans up a lot of other navigator code too. Test with `auth` branch in templates.
=> fix: remove auth navigation headers

packages/apollos-data-connector-rock/src/feature-feeds/index.js, packages/apollos-data-schema/src/index.js
Gives us a simple way to create more queries for more tabs without polluting the schema
test using the `tab-component` branch on templates
=> feat: add new tab feed query

packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap, packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js, packages/apollos-data-connector-rock/src/content-items/data-source.js
Looks at the parent content item to determine if comments should be enabled, as well as the item itself 
Code copied over from Newspring, which will be able to eliminate custom code after this is merged.
=> feat: get comment feature from parents

packages/apollos-data-connector-rock/src/personal-devices/data-source.js
In GraphQL Playground, run 
`mutation addDevice {
updateUserPushSettings (input: { pushProviderUserId: "arbitrary id"}) {
id
}
}`
=> chore: Dynamically look up Rock device mobile type ID on user registration

packages/apollos-ui-mapview/src/utils/getUserLocation.js
CF got this denial on trying to ship an app update:
> We noticed your app encourages or directs users to allow the app to access the location. Specifically, your app directs the user to grant permission in the following way(s):
> - A message asks the user to go to the Settings app and grant access after they deny permission.
Permission requests give users control of their personal information. It is important to respect their decision about how their data is used
It appears that if a user selects "No" to permissions we show an alert dialog letting them know that we won't be able to use their location. I believe simply turning these alerts to _off_ will fix this denial, and the app still fundamentally works.
@vinnyjth why did we add these alerts int he first place? do you remember what we …
=> fix: remove forced location permissions

packages/apollos-ui-connected/src/ConnectScreenConnected/index.js, packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeedConnected.js
Not really sure if this will fix anything but it's at least a step in the right direction. Currently, the liked content list isn't right on a production app. 
This insures that it's being refetched with the rest of it.
=> fix: properly refetch liked content list

packages/apollos-ui-connected/src/SearchScreenConnected/SearchScreenConnected.js
Need to get a discussion going here. Current approach works well but is a bit of a hack. 
To test, `BRANCH=search-connected yarn app`
=> fix: Close search modal when tapping on an item

packages/apollos-ui-kit/src/inputs/DateInput/index.js
Can't figure out how the background color of the box is determined but on a black ground, it looks bad. The defaults seem fine. No snaps changed. Check the core app with `yarn app`
=> chore: remove custom datepicker text color

packages/apollos-data-connector-rock/src/action-algorithms/index.js
I'm ok overriding the default sort like this because the purpose of this algorithm is to pull the most recent
=> fix: correctly sorts latest series children

packages/apollos-ui-onboarding/src/Onboarding/index.js
react-navigation doesn't like it when you pass functions as params
=> fix: remove ability to pass slides as route params

packages/apollos-data-connector-postgres/src/media/migrations/001_create_media.js, packages/apollos-data-connector-postgres/src/media/migrations/002_update_media_primary_keys.js, packages/apollos-data-connector-postgres/src/media/migrations/003_add_id_to_media.js, packages/apollos-data-connector-postgres/src/media/migrations/index.js, packages/apollos-data-connector-postgres/src/media/model.js
1. Migration was't running because there were two primary keys (`originId` can't also be a primary key) 
2. `hasOne` expects there to be a primary key on ContentItem. I don't think we need to setup the media.contentItem relationship at this point
3. Added a few fields that were missing in the model via a migration.
=> fix: Postgres Media bugfixes

packages/apollos-ui-kit/src/theme/OLD_theme.js, packages/apollos-ui-kit/src/theme/Themer.js, packages/apollos-ui-kit/src/theme/Themer.tests.js, packages/apollos-ui-kit/src/theme/__snapshots__/Themer.tests.js.snap
#1814 introduced a few regressions to the way themes are merged, and with #1838 using `useTheme` more extensively, it became pretty quickly clear of the issues.
Theming is hard.
I like to think of our theming system as having two parts - a theme input, and a theme object. A theme input is used to generate a theme object.
For example, if I do something like `<Themer theme={{ type: 'dark' }} />` you'd expect `Themer` to create a theme with the dark color scheme. In this case, `{ type: 'dark' }` is the theme input, and the resulting theme object with a dark color scheme is the generated theme.
Currently in master we are merging generated themes with theme inputs, resulting in incorrect themes getting generated. Example:
```jsx
<Themer theme={{ type: 'dark' }}>
<Themer theme={{ type: 'light' …
```
=> fix: Fix theme merging

packages/apollos-server-core/src/index.js
@redreceipt this stops the wild goose chase for tracking down packages with bad imports way easier. stops the old `can't call property dataSource of undefined` error
=> chore: Use more helpful error messages when package imports are wrong

packages/apollos-ui-kit/src/ConnectedImage/index.js
This fixes a race condition in the way ConnectedImage detects image size that I've only been able to replicate on River Valley and FNWA apps. The issue causes non-square images to be square the first time you open a content single with that image. The next time you open it, the image is the proper aspect ratio.
Here's my best explanation of what happens...but you should reference the first few lines in `ConnectedImage` component that's on master, here they are:
```jsx
const ConnectedImage = ({
source,
// ...otherProps
}) => {
const cachedSource = getCachedSources(source); // This gets a "cached" version of our source image that contains width and height keys
const imageInCache = every( // used to determine whether `handleOnLoad` callback below should run
cachedSource,
(image) => …
```
=> Fix: race condition in ConnectedImage loading

packages/apollos-data-connector-rock/package.json
prevents `Event.title not in schema` error
=> chore: data-schema peer dep

packages/apollos-data-connector-postgres/src/content-items/dataSource.js
Added order to the Sequelize query for getFromCategoryIds. This makes the most recent items return from Postgres. May need to add the order option to the other queries.
=> fix: Added Order to the contentItems
